# StatsPAI 因果推断演示 —— 交互式版本

本 Notebook 演示了核心因果推断方法，并支持**交互式图表编辑**。

每张图表都通过 `sp.interactive(fig)` 打开一个 ipywidgets 控制面板，您可以：
- 编辑标题、标签、字体、颜色、线条样式
- 调整 DPI、图形大小、刻度旋转、背景色
- 添加注释，切换网格 / 图例 / 边框
- 生成所有编辑的可复现代码

**涵盖的方法：**

1. **双重差分法 (DID)** —— 经典 2×2 设计与事件研究
2. **固定效应模型 (FE)** —— 面板数据实体固定效应
3. **工具变量法 (IV)** —— 两阶段最小二乘估计
4. **匹配法 (Matching)** —— 倾向得分匹配
5. **合成控制法 (SC)** —— Abadie 式合成控制
6. **断点回归设计 (RDD)** —— 精确断点回归
7. **分箱散点图 (Binscatter)** —— 非参数条件均值可视化

In [1]:
# 导入依赖库，设置随机种子与学术主题
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statspai as sp

np.random.seed(42)
sp.set_theme('academic')
# 为图内中文指定可用的中文衬线字体，并修正负号显示
sp.use_chinese('serif')
%matplotlib inline

---
## 1. 双重差分法 (DID)

经典 2×2 双重差分设计，包含平行趋势可视化和交错处理事件研究。

In [2]:
# 模拟 DID 数据：2×2 设计
# 200 个个体，10 个时间段，处理组从 t=6 开始接受处理
n_did = 200
t_periods = 10
ids = np.repeat(np.arange(n_did), t_periods)
times = np.tile(np.arange(1, t_periods + 1), n_did)
treat_group = (ids < 100).astype(int)  # 前 100 个个体为处理组
post = (times >= 6).astype(int)

# 处理前满足平行趋势，处理后处理效应为 3.0
individual_fe = np.repeat(np.random.normal(0, 2, n_did), t_periods)
time_trend = 0.5 * times
y_did = 10 + 2 * treat_group + time_trend + 3.0 * treat_group * post + individual_fe + np.random.normal(0, 1.5, n_did * t_periods)

df_did = pd.DataFrame({
    'id': ids, 'time': times, 'treated': treat_group,
    'post': post, 'outcome': y_did,
    'x1': np.random.normal(0, 1, n_did * t_periods),
})
print(f"样本量: {df_did.shape}，处理组个体数: {(ids < 100).sum() // t_periods}")
df_did.head()

样本量: (2000, 6)，处理组个体数: 100

   id  time  treated  post    outcome        x1
0   0     1        1     0  14.030109  1.804348
1   0     2        1     0  14.834605 -0.190904
2   0     3        1     0  16.118005  0.719758
3   0     4        1     0  16.574131 -1.293273
4   0     5        1     0  13.426924 -0.956436

In [3]:
# 2×2 双重差分估计
did_result = sp.did(
    df_did, y='outcome', treat='treated', time='time',
    id='id', method='classic'
)
did_result

In [4]:
# 绘图 1：DID 平行趋势 —— 处理组与控制组各期均值
fig, ax = sp.did_plot(
    df_did, y='outcome', time='time', treat='treated',
    treat_time=6,
    labels={'treated': '处理组', 'control': '控制组'},
    title='双重差分：平行趋势与处理效应',
    annotate_effect=True,
)
# # --- StatsPAI 交互式编辑（粘贴到绘图代码之后）---
# import statspai as sp
# sp.set_theme('ggplot')
# fig.tight_layout()
# # --- StatsPAI 编辑结束 ---

sp.interactive(fig)

HBox(children=(VBox(children=(Image(value=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x03\xdc\x00\x00\x02K\x…

FigureEditor(fig=<Figure size 1500x900 with 1 Axes>, protect_data=True, edits=[], artist_roles={2132773273088: <ArtistRole.LABEL: 5>, 2132773270832: <ArtistRole.LABEL: 5>, 2132773271744: <ArtistRole.LABEL: 5>, 2132773269824: <ArtistRole.SPINE: 8>, 2132773269728: <ArtistRole.SPINE: 8>, 2132773270064: <ArtistRole.SPINE: 8>, 2132773270304: <ArtistRole.SPINE: 8>, 2132773669728: <ArtistRole.LEGEND: 7>, 2132771296400: <ArtistRole.DATA: 1>, 2132773679904: <ArtistRole.REFERENCE: 4>, 2132773682400: <ArtistRole.DATA: 1>, 2132751164688: <ArtistRole.REFERENCE: 4>, 2132751866560: <ArtistRole.ANNOTATION: 6>, 2132773682880: <ArtistRole.ANNOTATION: 6>, 2132773897760: <ArtistRole.ANNOTATION: 6>}, _original_state={'ax.title.text': '双重差分：平行趋势与处理效应', 'ax.title.fontsize': 13.0, 'ax.title.color': 'black', 'ax.title.fontweight': 'normal', 'ax.xlabel.text': 'Time', 'ax.xlabel.fontsize': 11.0, 'ax.xlabel.color': 'black', 'ax.ylabel.text': 'Outcome', 'ax.ylabel.fontsize': 11.0, 'ax.ylabel.color': 'black', 'ax.xlim': (np.float64(0.55), np.float64(10.45)), 'ax.ylim': (np.float64(10.157882537037665), np.float64(20.502018931687)), 'ax.facecolor': (1.0, 1.0, 1.0, 1.0), 'ax.xtick_rotation': 0.0, 'ax.ytick_rotation': 0.0, 'ax.spines.left.visible': True, 'ax.spines.right.visible': False, 'ax.spines.bottom.visible': True, 'ax.spines.top.visible': False, 'ax.grid': False, 'ax.line0.color': '#2C3E50', 'ax.line0.linewidth': 2.0, 'ax.line0.linestyle': '-', 'ax.line0.alpha': None, 'ax.line0.marker': 's', 'ax.line1.color': '#E74C3C', 'ax.line1.linewidth': 2.0, 'ax.line1.linestyle': '-', 'ax.line1.alpha': None, 'ax.line1.marker': 'o', 'ax.line2.color': '#E74C3C', 'ax.line2.linewidth': 1.5, 'ax.line2.linestyle': '--', 'ax.line2.alpha': 0.7, 'ax.line2.marker': '', 'ax.line3.color': 'gray', 'ax.line3.linewidth': 1.0, 'ax.line3.linestyle': ':', 'ax.line3.alpha': 0.5, 'ax.line3.marker': 'None', 'ax.n_texts': 3, 'fig.figsize': (np.float64(10.0), np.float64(6.0)), 'fig.dpi': 150.0, 'fig.facecolor': (1.0, 1.0, 1.0, 1.0)}, _on_refresh_callbacks=[<function create_jupyter_panel.<locals>._live_refresh at 0x000001F095D01620>, <function create_jupyter_panel.<locals>._live_history_update at 0x000001F095693C40>, <function create_jupyter_panel.<locals>._live_code_update at 0x000001F0956DCC20>], _redo_stack=[])

In [5]:
# 绘图 2：使用 Callaway-Sant'Anna 方法的事件研究
# 需要交错处理编码：first_treat = 首次处理时期（0 = 从未处理）
df_did['first_treat'] = np.where(df_did['treated'] == 1, 6, 0)

es_result = sp.did(
    df_did, y='outcome', treat='first_treat', time='time',
    id='id', method='cs'
)
fig, ax = es_result.plot(type='event_study',
    title='双重差分事件研究：动态处理效应',
    color='#1a5276',
)
sp.interactive(fig)

HBox(children=(VBox(children=(Image(value=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x03\xda\x00\x00\x02K\x…

FigureEditor(fig=<Figure size 1500x900 with 1 Axes>, protect_data=True, edits=[], artist_roles={2132817932320: <ArtistRole.LABEL: 5>, 2132810536272: <ArtistRole.LABEL: 5>, 2132810533296: <ArtistRole.LABEL: 5>, 2132810543664: <ArtistRole.SPINE: 8>, 2132810544288: <ArtistRole.SPINE: 8>, 2132810546064: <ArtistRole.SPINE: 8>, 2132810536800: <ArtistRole.SPINE: 8>, 2132817650672: <ArtistRole.LEGEND: 7>, 2132773087728: <ArtistRole.DATA: 1>, 2132817193312: <ArtistRole.REFERENCE: 4>, 2132817197632: <ArtistRole.REFERENCE: 4>, 2132810698720: <ArtistRole.REFERENCE: 4>, 2132817186640: <ArtistRole.REFERENCE: 4>, 2132810703136: <ArtistRole.CI: 3>, 2132817644528: <ArtistRole.DATA: 1>, 2132817198400: <ArtistRole.CI: 3>}, _original_state={'ax.title.text': '双重差分事件研究：动态处理效应', 'ax.title.fontsize': 13.0, 'ax.title.color': 'black', 'ax.title.fontweight': 'normal', 'ax.xlabel.text': 'Periods Relative to Treatment', 'ax.xlabel.fontsize': 11.0, 'ax.xlabel.color': 'black', 'ax.ylabel.text': 'Estimated Effect', 'ax.ylabel.fontsize': 11.0, 'ax.ylabel.color': 'black', 'ax.xlim': (np.float64(-5.45), np.float64(4.45)), 'ax.ylim': (np.float64(-1.365419279546503), np.float64(3.744231062105696)), 'ax.facecolor': (1.0, 1.0, 1.0, 1.0), 'ax.xtick_rotation': 0.0, 'ax.ytick_rotation': 0.0, 'ax.spines.left.visible': True, 'ax.spines.right.visible': False, 'ax.spines.bottom.visible': True, 'ax.spines.top.visible': False, 'ax.grid': False, 'ax.line0.color': '#1a5276', 'ax.line0.linewidth': 1.0, 'ax.line0.linestyle': '-', 'ax.line0.alpha': 0.7, 'ax.line0.marker': 'None', 'ax.line1.color': '#1a5276', 'ax.line1.linewidth': 1.0, 'ax.line1.linestyle': 'None', 'ax.line1.alpha': None, 'ax.line1.marker': '_', 'ax.line2.color': '#1a5276', 'ax.line2.linewidth': 1.0, 'ax.line2.linestyle': 'None', 'ax.line2.alpha': None, 'ax.line2.marker': '_', 'ax.line3.color': 'gray', 'ax.line3.linewidth': 0.8, 'ax.line3.linestyle': '--', 'ax.line3.alpha': None, 'ax.line3.marker': 'None', 'ax.line4.color': '#E74C3C', 'ax.line4.linewidth': 1.0, 'ax.line4.linestyle': ':', 'ax.line4.alpha': 0.5, 'ax.line4.marker': 'None', 'ax.coll0.alpha': 0.15, 'ax.coll0.facecolors': array([[0.10196078, 0.32156863, 0.4627451 , 0.15      ]]), 'ax.coll1.alpha': None, 'ax.coll1.facecolors': array([[0.10196078, 0.32156863, 0.4627451 , 1.        ]]), 'ax.coll2.alpha': None, 'ax.coll2.facecolors': array([], shape=(0, 4), dtype=float64), 'ax.n_texts': 0, 'fig.figsize': (np.float64(10.0), np.float64(6.0)), 'fig.dpi': 150.0, 'fig.facecolor': (1.0, 1.0, 1.0, 1.0)}, _on_refresh_callbacks=[<function create_jupyter_panel.<locals>._live_refresh at 0x000001F0956D4540>, <function create_jupyter_panel.<locals>._live_history_update at 0x000001F0957F2FC0>, <function create_jupyter_panel.<locals>._live_code_update at 0x000001F0957F3E20>], _redo_stack=[])

---
## 2. 固定效应模型 (FE)

面板数据：100 家企业观测 10 年。处理变量 `policy`（政策）采用交错实施。

In [6]:
# 模拟面板数据：100 家企业，10 年
n_firms, n_years = 100, 10
firms = np.repeat(np.arange(n_firms), n_years)
years = np.tile(np.arange(2010, 2010 + n_years), n_firms)
firm_fe = np.repeat(np.random.normal(0, 2, n_firms), n_years)
x1 = np.random.normal(5, 1, n_firms * n_years)
x2 = np.random.normal(0, 1, n_firms * n_years)
policy = ((years >= 2015) & (firms < 50)).astype(int)
y_panel = 3 + 2.5 * x1 - 1.2 * x2 + 1.8 * policy + firm_fe + np.random.normal(0, 1, n_firms * n_years)

df_panel = pd.DataFrame({
    'firm_id': firms, 'year': years,
    'revenue': y_panel, 'investment': x1, 'debt_ratio': x2, 'policy': policy
})
df_panel.head()

   firm_id  year    revenue  investment  debt_ratio  policy
0        0  2010  14.957120    4.576401   -0.208668       0
1        0  2011  11.507491    3.634383   -0.312668       0
2        0  2012  13.481348    4.025878    0.857899       0
3        0  2013  18.209287    5.703428    0.553570       0
4        0  2014  11.080308    3.692630   -0.257300       0

In [7]:
# 固定效应回归
fe_result = sp.panel(
    df_panel,
    "revenue ~ investment + debt_ratio + policy",
    entity='firm_id', time='year', method='fe'
)
fe_result

In [8]:
# Hausman 检验：固定效应 vs 随机效应
fe_result.hausman_test()

{'statistic': 0.2963862286170517,
 'df': 3,
 'pvalue': 0.960706694278104,
 'recommendation': 'RE',
 'beta_fe': investment    2.532736
 debt_ratio   -1.168082
 policy        2.013911
 dtype: float64,
 'beta_re': investment    2.532659
 debt_ratio   -1.168357
 policy        2.009315
 dtype: float64,
 'interpretation': 'chi2(3) = 0.2964, p = 0.9607. Cannot reject H0: Random Effects is more efficient.'}

In [9]:
# 绘图：系数森林图
fig, ax = sp.coefplot(fe_result, title='固定效应：系数图')
sp.interactive(fig)

HBox(children=(VBox(children=(Image(value=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x03\x13\x00\x00\x02J\x…

FigureEditor(fig=<Figure size 1200x900 with 1 Axes>, protect_data=True, edits=[], artist_roles={2132828585088: <ArtistRole.LABEL: 5>, 2132828580480: <ArtistRole.LABEL: 5>, 2132828581536: <ArtistRole.LABEL: 5>, 2132828578992: <ArtistRole.SPINE: 8>, 2132828579280: <ArtistRole.SPINE: 8>, 2132828579568: <ArtistRole.SPINE: 8>, 2132828579856: <ArtistRole.SPINE: 8>, 2132828718816: <ArtistRole.LEGEND: 7>, 2132828730000: <ArtistRole.REFERENCE: 4>, 2132827878176: <ArtistRole.REFERENCE: 4>, 2132828578224: <ArtistRole.REFERENCE: 4>, 2132828026592: <ArtistRole.DATA: 1>, 2132828026832: <ArtistRole.CI: 3>}, _original_state={'ax.title.text': '固定效应：系数图', 'ax.title.fontsize': 13.0, 'ax.title.color': 'black', 'ax.title.fontweight': 'normal', 'ax.xlabel.text': 'Coefficient Estimate', 'ax.xlabel.fontsize': 11.0, 'ax.xlabel.color': 'black', 'ax.ylabel.text': '', 'ax.ylabel.fontsize': 11.0, 'ax.ylabel.color': 'black', 'ax.xlim': (np.float64(-1.4270658370199156), np.float64(2.7936456216609713)), 'ax.ylim': (np.float64(2.1), np.float64(-0.1)), 'ax.facecolor': (1.0, 1.0, 1.0, 1.0), 'ax.xtick_rotation': 0.0, 'ax.ytick_rotation': 0.0, 'ax.spines.left.visible': True, 'ax.spines.right.visible': False, 'ax.spines.bottom.visible': True, 'ax.spines.top.visible': False, 'ax.grid': False, 'ax.line0.color': '#2C3E50', 'ax.line0.linewidth': 1.0, 'ax.line0.linestyle': 'None', 'ax.line0.alpha': None, 'ax.line0.marker': '|', 'ax.line1.color': '#2C3E50', 'ax.line1.linewidth': 1.0, 'ax.line1.linestyle': 'None', 'ax.line1.alpha': None, 'ax.line1.marker': '|', 'ax.line2.color': 'gray', 'ax.line2.linewidth': 0.8, 'ax.line2.linestyle': '--', 'ax.line2.alpha': None, 'ax.line2.marker': 'None', 'ax.coll0.alpha': None, 'ax.coll0.facecolors': array([[0.17254902, 0.24313725, 0.31372549, 1.        ]]), 'ax.coll1.alpha': None, 'ax.coll1.facecolors': array([], shape=(0, 4), dtype=float64), 'ax.n_texts': 0, 'fig.figsize': (np.float64(8.0), np.float64(6.0)), 'fig.dpi': 150.0, 'fig.facecolor': (1.0, 1.0, 1.0, 1.0)}, _on_refresh_callbacks=[<function create_jupyter_panel.<locals>._live_refresh at 0x000001F09681E700>, <function create_jupyter_panel.<locals>._live_history_update at 0x000001F098B28E00>, <function create_jupyter_panel.<locals>._live_code_update at 0x000001F098B29D00>], _redo_stack=[])

In [10]:
# 绘图：对比固定效应、随机效应和混合回归的系数
re_result = sp.panel(df_panel, "revenue ~ investment + debt_ratio + policy",
                     entity='firm_id', time='year', method='re')
pooled_result = sp.panel(df_panel, "revenue ~ investment + debt_ratio + policy",
                         entity='firm_id', time='year', method='pooled')

fig, ax = sp.coefplot(fe_result, re_result, pooled_result,
                      model_names=['固定效应', '随机效应', '混合回归'],
                      title='面板模型：系数对比')
sp.interactive(fig)

HBox(children=(VBox(children=(Image(value=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x03\x13\x00\x00\x02J\x…

FigureEditor(fig=<Figure size 1200x900 with 1 Axes>, protect_data=True, edits=[], artist_roles={2132829105344: <ArtistRole.LABEL: 5>, 2132829196400: <ArtistRole.LABEL: 5>, 2132829194864: <ArtistRole.LABEL: 5>, 2132829198224: <ArtistRole.SPINE: 8>, 2132829197600: <ArtistRole.SPINE: 8>, 2132829197408: <ArtistRole.SPINE: 8>, 2132829196880: <ArtistRole.SPINE: 8>, 2132829102704: <ArtistRole.LEGEND: 7>, 2132865825104: <ArtistRole.REFERENCE: 4>, 2132829202208: <ArtistRole.REFERENCE: 4>, 2132866011536: <ArtistRole.REFERENCE: 4>, 2132866007456: <ArtistRole.REFERENCE: 4>, 2132866015952: <ArtistRole.REFERENCE: 4>, 2132866017056: <ArtistRole.REFERENCE: 4>, 2132829199472: <ArtistRole.REFERENCE: 4>, 2132829194288: <ArtistRole.DATA: 1>, 2132865823232: <ArtistRole.CI: 3>, 2132866007600: <ArtistRole.DATA: 1>, 2132866008800: <ArtistRole.CI: 3>, 2132866013600: <ArtistRole.DATA: 1>, 2132866015808: <ArtistRole.CI: 3>}, _original_state={'ax.title.text': '面板模型：系数对比', 'ax.title.fontsize': 13.0, 'ax.title.color': 'black', 'ax.title.fontweight': 'normal', 'ax.xlabel.text': 'Coefficient Estimate', 'ax.xlabel.fontsize': 11.0, 'ax.xlabel.color': 'black', 'ax.ylabel.text': '', 'ax.ylabel.fontsize': 11.0, 'ax.ylabel.color': 'black', 'ax.xlim': (np.float64(-1.5513547099021263), np.float64(3.502040550440085)), 'ax.ylim': (np.float64(3.465), np.float64(-0.165)), 'ax.facecolor': (1.0, 1.0, 1.0, 1.0), 'ax.xtick_rotation': 0.0, 'ax.ytick_rotation': 0.0, 'ax.spines.left.visible': True, 'ax.spines.right.visible': False, 'ax.spines.bottom.visible': True, 'ax.spines.top.visible': False, 'ax.grid': False, 'ax.line0.color': '#2C3E50', 'ax.line0.linewidth': 1.0, 'ax.line0.linestyle': 'None', 'ax.line0.alpha': None, 'ax.line0.marker': '|', 'ax.line1.color': '#2C3E50', 'ax.line1.linewidth': 1.0, 'ax.line1.linestyle': 'None', 'ax.line1.alpha': None, 'ax.line1.marker': '|', 'ax.line2.color': '#E74C3C', 'ax.line2.linewidth': 1.0, 'ax.line2.linestyle': 'None', 'ax.line2.alpha': None, 'ax.line2.marker': '|', 'ax.line3.color': '#E74C3C', 'ax.line3.linewidth': 1.0, 'ax.line3.linestyle': 'None', 'ax.line3.alpha': None, 'ax.line3.marker': '|', 'ax.line4.color': '#3498DB', 'ax.line4.linewidth': 1.0, 'ax.line4.linestyle': 'None', 'ax.line4.alpha': None, 'ax.line4.marker': '|', 'ax.line5.color': '#3498DB', 'ax.line5.linewidth': 1.0, 'ax.line5.linestyle': 'None', 'ax.line5.alpha': None, 'ax.line5.marker': '|', 'ax.line6.color': 'gray', 'ax.line6.linewidth': 0.8, 'ax.line6.linestyle': '--', 'ax.line6.alpha': None, 'ax.line6.marker': 'None', 'ax.coll0.alpha': None, 'ax.coll0.facecolors': array([[0.17254902, 0.24313725, 0.31372549, 1.        ]]), 'ax.coll1.alpha': None, 'ax.coll1.facecolors': array([], shape=(0, 4), dtype=float64), 'ax.coll2.alpha': None, 'ax.coll2.facecolors': array([[0.90588235, 0.29803922, 0.23529412, 1.        ]]), 'ax.coll3.alpha': None, 'ax.coll3.facecolors': array([], shape=(0, 4), dtype=float64), 'ax.coll4.alpha': None, 'ax.coll4.facecolors': array([[0.20392157, 0.59607843, 0.85882353, 1.        ]]), 'ax.coll5.alpha': None, 'ax.coll5.facecolors': array([], shape=(0, 4), dtype=float64), 'ax.n_texts': 0, 'fig.figsize': (np.float64(8.0), np.float64(6.0)), 'fig.dpi': 150.0, 'fig.facecolor': (1.0, 1.0, 1.0, 1.0)}, _on_refresh_callbacks=[<function create_jupyter_panel.<locals>._live_refresh at 0x000001F098B9E980>, <function create_jupyter_panel.<locals>._live_history_update at 0x000001F098E5FCE0>, <function create_jupyter_panel.<locals>._live_code_update at 0x000001F098EBCAE0>], _redo_stack=[])

---
## 3. 工具变量法 (IV)

经典的教育回报率案例：`education`（教育年限）为内生变量，`distance_to_college`（到大学的距离）为工具变量。

In [11]:
# 模拟工具变量数据
# ability（能力）为不可观测变量，distance（距离）为工具变量
n_iv = 2000
ability = np.random.normal(0, 1, n_iv)  # 不可观测
distance = np.random.normal(50, 20, n_iv)  # 工具变量
experience = np.random.normal(10, 3, n_iv)
education = 16 - 0.08 * distance + 0.5 * ability + np.random.normal(0, 1, n_iv)
wage = 10 + 0.8 * education + 0.3 * experience + 0.6 * ability + np.random.normal(0, 2, n_iv)

df_iv = pd.DataFrame({
    'wage': wage, 'education': education,
    'experience': experience, 'distance': distance
})
df_iv.head()

        wage  education  experience   distance
0  16.860593  11.152590   10.657927  58.424948
1  23.263697  10.456267   10.105886  66.936799
2  21.417441  10.372786    7.831496  60.686944
3  23.347924  15.824814    3.473354  14.631691
4  20.524002   8.772993    7.021394  69.903353

In [12]:
# OLS 回归（因遗漏能力变量而存在偏误）
ols_result = sp.regress("wage ~ education + experience", data=df_iv)
ols_result

In [13]:
# 两阶段最小二乘 (2SLS) 工具变量估计
# 公式：y ~ (内生变量 ~ 工具变量) + 外生控制变量
iv_result = sp.ivreg(
    "wage ~ (education ~ distance) + experience",
    data=df_iv
)
iv_result

In [14]:
# 绘图：并排比较 OLS 与 IV 系数
fig, ax = sp.coefplot(ols_result, iv_result,
                      model_names=['OLS（有偏）', '2SLS IV（一致）'],
                      colors=['#E74C3C', '#2C3E50'],
                      title='OLS 与 IV：教育回报率')
sp.interactive(fig)

HBox(children=(VBox(children=(Image(value=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x03\x13\x00\x00\x02K\x…

FigureEditor(fig=<Figure size 1200x900 with 1 Axes>, protect_data=True, edits=[], artist_roles={2132896638416: <ArtistRole.LABEL: 5>, 2132896631504: <ArtistRole.LABEL: 5>, 2132896632704: <ArtistRole.LABEL: 5>, 2132896629872: <ArtistRole.SPINE: 8>, 2132896630256: <ArtistRole.SPINE: 8>, 2132896630544: <ArtistRole.SPINE: 8>, 2132896630832: <ArtistRole.SPINE: 8>, 2132827409776: <ArtistRole.LEGEND: 7>, 2132896812352: <ArtistRole.REFERENCE: 4>, 2132896812064: <ArtistRole.REFERENCE: 4>, 2132896820848: <ArtistRole.REFERENCE: 4>, 2132896821376: <ArtistRole.REFERENCE: 4>, 2132896508256: <ArtistRole.REFERENCE: 4>, 2132868953632: <ArtistRole.DATA: 1>, 2132896812016: <ArtistRole.CI: 3>, 2132896816480: <ArtistRole.DATA: 1>, 2132896818640: <ArtistRole.CI: 3>}, _original_state={'ax.title.text': 'OLS 与 IV：教育回报率', 'ax.title.fontsize': 13.0, 'ax.title.color': 'black', 'ax.title.fontweight': 'normal', 'ax.xlabel.text': 'Coefficient Estimate', 'ax.xlabel.fontsize': 11.0, 'ax.xlabel.color': 'black', 'ax.ylabel.text': '', 'ax.ylabel.fontsize': 11.0, 'ax.ylabel.color': 'black', 'ax.xlim': (np.float64(-0.2768092924916755), np.float64(11.350446720081731)), 'ax.ylim': (np.float64(2.2649999999999997), np.float64(-0.265)), 'ax.facecolor': (1.0, 1.0, 1.0, 1.0), 'ax.xtick_rotation': 0.0, 'ax.ytick_rotation': 0.0, 'ax.spines.left.visible': True, 'ax.spines.right.visible': False, 'ax.spines.bottom.visible': True, 'ax.spines.top.visible': False, 'ax.grid': False, 'ax.line0.color': '#E74C3C', 'ax.line0.linewidth': 1.0, 'ax.line0.linestyle': 'None', 'ax.line0.alpha': None, 'ax.line0.marker': '|', 'ax.line1.color': '#E74C3C', 'ax.line1.linewidth': 1.0, 'ax.line1.linestyle': 'None', 'ax.line1.alpha': None, 'ax.line1.marker': '|', 'ax.line2.color': '#2C3E50', 'ax.line2.linewidth': 1.0, 'ax.line2.linestyle': 'None', 'ax.line2.alpha': None, 'ax.line2.marker': '|', 'ax.line3.color': '#2C3E50', 'ax.line3.linewidth': 1.0, 'ax.line3.linestyle': 'None', 'ax.line3.alpha': None, 'ax.line3.marker': '|', 'ax.line4.color': 'gray', 'ax.line4.linewidth': 0.8, 'ax.line4.linestyle': '--', 'ax.line4.alpha': None, 'ax.line4.marker': 'None', 'ax.coll0.alpha': None, 'ax.coll0.facecolors': array([[0.90588235, 0.29803922, 0.23529412, 1.        ]]), 'ax.coll1.alpha': None, 'ax.coll1.facecolors': array([], shape=(0, 4), dtype=float64), 'ax.coll2.alpha': None, 'ax.coll2.facecolors': array([[0.17254902, 0.24313725, 0.31372549, 1.        ]]), 'ax.coll3.alpha': None, 'ax.coll3.facecolors': array([], shape=(0, 4), dtype=float64), 'ax.n_texts': 0, 'fig.figsize': (np.float64(8.0), np.float64(6.0)), 'fig.dpi': 150.0, 'fig.facecolor': (1.0, 1.0, 1.0, 1.0)}, _on_refresh_callbacks=[<function create_jupyter_panel.<locals>._live_refresh at 0x000001F09A906CA0>, <function create_jupyter_panel.<locals>._live_history_update at 0x000001F09A905C60>, <function create_jupyter_panel.<locals>._live_code_update at 0x000001F09AE43E20>], _redo_stack=[])

---
## 4. 匹配法 (Matching)

就业培训项目评估：使用倾向得分匹配估计处理组平均处理效应（ATT）。

In [15]:
# 模拟匹配数据：就业培训项目
n_match = 1000
age = np.random.normal(35, 8, n_match)
edu_years = np.random.normal(12, 3, n_match)
prior_earn = np.random.normal(30000, 8000, n_match)

# 处理分配依赖于协变量（存在选择偏差）
propensity = 1 / (1 + np.exp(-(- 2 + 0.05 * age - 0.1 * edu_years + 0.00005 * prior_earn)))
treatment = np.random.binomial(1, propensity)

# 结果变量：处理效应为 2000
earnings = 25000 + 500 * edu_years + 100 * age + 0.5 * prior_earn + 2000 * treatment + np.random.normal(0, 3000, n_match)

df_match = pd.DataFrame({
    'earnings': earnings, 'treatment': treatment,
    'age': age, 'edu_years': edu_years, 'prior_earn': prior_earn
})
print(f"处理组: {treatment.sum()}，控制组: {(1-treatment).sum()}")
df_match.head()

处理组: 485，控制组: 515

       earnings  treatment        age  edu_years    prior_earn
0  52592.516393          1  20.702891  13.150965  41327.285124
1  51203.815118          1  26.931754   9.365591  38008.518741
2  45276.029806          0  33.025137   8.042484  32374.616868
3  51692.670654          0  22.516532  11.528465  28293.692693
4  56786.043023          0  43.897193  10.427315  36819.271022

In [16]:
# 倾向得分匹配
match_result = sp.match(
    df_match,
    y='earnings', treat='treatment',
    covariates=['age', 'edu_years', 'prior_earn'],
    distance='propensity', method='nearest',
    n_matches=3, caliper=0.2
)
match_result

C:\Users\capen\AppData\Local\Temp\ipykernel_35600\1550096055.py:2: UserWarning: PSM can increase imbalance and bias (King & Nielsen 2019). Consider distance='mahalanobis' or method='cem'.
  match_result = sp.match(

In [17]:
# 绘图：Love 图（匹配前后协变量平衡性）
fig, ax = sp.balanceplot(match_result, title='协变量平衡性：Love 图')
sp.interactive(fig)

HBox(children=(VBox(children=(Image(value=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x03\x13\x00\x00\x01\x8…

FigureEditor(fig=<Figure size 1200x600 with 1 Axes>, protect_data=True, edits=[], artist_roles={2132901530896: <ArtistRole.LABEL: 5>, 2132869247392: <ArtistRole.LABEL: 5>, 2132901536752: <ArtistRole.LABEL: 5>, 2132899019856: <ArtistRole.SPINE: 8>, 2132896944816: <ArtistRole.SPINE: 8>, 2132896633232: <ArtistRole.SPINE: 8>, 2132869236736: <ArtistRole.SPINE: 8>, 2132902365760: <ArtistRole.REFERENCE: 4>, 2132901469920: <ArtistRole.REFERENCE: 4>, 2132901641152: <ArtistRole.REFERENCE: 4>, 2132902377184: <ArtistRole.DATA: 1>, 2132901478272: <ArtistRole.COSMETIC: 9>, 2132902376656: <ArtistRole.COSMETIC: 9>, 2132899014960: <ArtistRole.COSMETIC: 9>, 2132901631840: <ArtistRole.COSMETIC: 9>}, _original_state={'ax.title.text': '协变量平衡性：Love 图', 'ax.title.fontsize': 13.0, 'ax.title.color': 'black', 'ax.title.fontweight': 'normal', 'ax.xlabel.text': 'Standardized Mean Difference (SMD)', 'ax.xlabel.fontsize': 11.0, 'ax.xlabel.color': 'black', 'ax.ylabel.text': '', 'ax.ylabel.fontsize': 11.0, 'ax.ylabel.color': 'black', 'ax.xlim': (np.float64(-0.31018), np.float64(0.6265799999999999)), 'ax.ylim': (np.float64(3.1610000000000005), np.float64(-0.16100000000000003)), 'ax.facecolor': (1.0, 1.0, 1.0, 1.0), 'ax.xtick_rotation': 0.0, 'ax.ytick_rotation': 0.0, 'ax.spines.left.visible': True, 'ax.spines.right.visible': False, 'ax.spines.bottom.visible': True, 'ax.spines.top.visible': False, 'ax.grid': False, 'ax.line0.color': '#E74C3C', 'ax.line0.linewidth': 0.8, 'ax.line0.linestyle': '--', 'ax.line0.alpha': 0.5, 'ax.line0.marker': 'None', 'ax.line1.color': '#E74C3C', 'ax.line1.linewidth': 0.8, 'ax.line1.linestyle': '--', 'ax.line1.alpha': 0.5, 'ax.line1.marker': 'None', 'ax.line2.color': 'gray', 'ax.line2.linewidth': 0.5, 'ax.line2.linestyle': '-', 'ax.line2.alpha': None, 'ax.line2.marker': 'None', 'ax.coll0.alpha': None, 'ax.coll0.facecolors': array([[0.90588235, 0.29803922, 0.23529412, 1.        ],
       [0.90588235, 0.29803922, 0.23529412, 1.        ],
       [0.90588235, 0.29803922, 0.23529412, 1.        ],
       [0.90588235, 0.29803922, 0.23529412, 1.        ]]), 'ax.n_texts': 0, 'fig.figsize': (np.float64(8.0), np.float64(4.0)), 'fig.dpi': 150.0, 'fig.facecolor': (1.0, 1.0, 1.0, 1.0)}, _on_refresh_callbacks=[<function create_jupyter_panel.<locals>._live_refresh at 0x000001F09AB4FD80>, <function create_jupyter_panel.<locals>._live_history_update at 0x000001F09AB7CFE0>, <function create_jupyter_panel.<locals>._live_code_update at 0x000001F09ABBF920>], _redo_stack=[])

In [18]:
# 绘图：倾向得分分布（共同支撑域）
fig, ax = sp.psplot(
    df_match, treat='treatment',
    covariates=['age', 'edu_years', 'prior_earn'],
    title='倾向得分分布',
    colors=('#3498DB', '#E74C3C'),
    labels=('控制组', '培训项目'),
)
sp.interactive(fig)

HBox(children=(VBox(children=(Image(value=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x03\x12\x00\x00\x01\xe…

FigureEditor(fig=<Figure size 1200x750 with 1 Axes>, protect_data=True, edits=[], artist_roles={2132898969792: <ArtistRole.LABEL: 5>, 2132899999584: <ArtistRole.LABEL: 5>, 2132899998144: <ArtistRole.LABEL: 5>, 2132900002224: <ArtistRole.SPINE: 8>, 2132900001744: <ArtistRole.SPINE: 8>, 2132900001264: <ArtistRole.SPINE: 8>, 2132900000784: <ArtistRole.SPINE: 8>, 2132902371616: <ArtistRole.LEGEND: 7>, 2132899651968: <ArtistRole.COSMETIC: 9>, 2132902377040: <ArtistRole.COSMETIC: 9>, 2132899650240: <ArtistRole.COSMETIC: 9>, 2132900259088: <ArtistRole.COSMETIC: 9>, 2132899655232: <ArtistRole.COSMETIC: 9>, 2132900257552: <ArtistRole.COSMETIC: 9>, 2132899646928: <ArtistRole.COSMETIC: 9>, 2132902016688: <ArtistRole.COSMETIC: 9>, 2132900254768: <ArtistRole.COSMETIC: 9>, 2132902378096: <ArtistRole.COSMETIC: 9>, 2132900253136: <ArtistRole.COSMETIC: 9>, 2132900252368: <ArtistRole.COSMETIC: 9>, 2132900251552: <ArtistRole.COSMETIC: 9>, 2132900250544: <ArtistRole.COSMETIC: 9>, 2132900249824: <ArtistRole.COSMETIC: 9>, 2132900260192: <ArtistRole.COSMETIC: 9>, 2132901538240: <ArtistRole.COSMETIC: 9>, 2132900261248: <ArtistRole.COSMETIC: 9>, 2132900261776: <ArtistRole.COSMETIC: 9>, 2132900262352: <ArtistRole.COSMETIC: 9>, 2132900262928: <ArtistRole.COSMETIC: 9>, 2132900263024: <ArtistRole.COSMETIC: 9>, 2132900263984: <ArtistRole.COSMETIC: 9>, 2132900264560: <ArtistRole.COSMETIC: 9>, 2132900265088: <ArtistRole.COSMETIC: 9>, 2132900265664: <ArtistRole.COSMETIC: 9>, 2132900250256: <ArtistRole.COSMETIC: 9>, 2132900627184: <ArtistRole.COSMETIC: 9>, 2132900627712: <ArtistRole.COSMETIC: 9>, 2132900628288: <ArtistRole.COSMETIC: 9>, 2132900628816: <ArtistRole.COSMETIC: 9>, 2132900629392: <ArtistRole.COSMETIC: 9>, 2132900629872: <ArtistRole.COSMETIC: 9>, 2132900264080: <ArtistRole.COSMETIC: 9>, 2132900630880: <ArtistRole.COSMETIC: 9>, 2132901634864: <ArtistRole.COSMETIC: 9>, 2132900631888: <ArtistRole.COSMETIC: 9>, 2132900632464: <ArtistRole.COSMETIC: 9>, 2132901476784: <ArtistRole.COSMETIC: 9>, 2132902067184: <ArtistRole.COSMETIC: 9>, 2132900630976: <ArtistRole.COSMETIC: 9>, 2132899652448: <ArtistRole.COSMETIC: 9>, 2132900635152: <ArtistRole.COSMETIC: 9>, 2132900635728: <ArtistRole.COSMETIC: 9>, 2132900636208: <ArtistRole.COSMETIC: 9>, 2132900636784: <ArtistRole.COSMETIC: 9>, 2132900637312: <ArtistRole.COSMETIC: 9>, 2132899991520: <ArtistRole.COSMETIC: 9>, 2132900637936: <ArtistRole.COSMETIC: 9>, 2132900638896: <ArtistRole.COSMETIC: 9>, 2132900264272: <ArtistRole.COSMETIC: 9>, 2132900639904: <ArtistRole.COSMETIC: 9>, 2132900640384: <ArtistRole.COSMETIC: 9>, 2132900640912: <ArtistRole.COSMETIC: 9>, 2132901533968: <ArtistRole.COSMETIC: 9>, 2132902058352: <ArtistRole.COSMETIC: 9>, 2132900642448: <ArtistRole.COSMETIC: 9>, 2132900905232: <ArtistRole.COSMETIC: 9>, 2132900905808: <ArtistRole.COSMETIC: 9>, 2132900906384: <ArtistRole.COSMETIC: 9>, 2132900627856: <ArtistRole.COSMETIC: 9>, 2132900907488: <ArtistRole.COSMETIC: 9>, 2132900252272: <ArtistRole.COSMETIC: 9>, 2132900633232: <ArtistRole.COSMETIC: 9>, 2132899650576: <ArtistRole.COSMETIC: 9>, 2132899987632: <ArtistRole.COSMETIC: 9>, 2132900909696: <ArtistRole.COSMETIC: 9>, 2132900255200: <ArtistRole.COSMETIC: 9>, 2132900910800: <ArtistRole.COSMETIC: 9>, 2132900911376: <ArtistRole.COSMETIC: 9>, 2132900256112: <ArtistRole.COSMETIC: 9>, 2132900254480: <ArtistRole.COSMETIC: 9>, 2132900912960: <ArtistRole.COSMETIC: 9>, 2132900913440: <ArtistRole.COSMETIC: 9>, 2132900914064: <ArtistRole.COSMETIC: 9>, 2132900914544: <ArtistRole.COSMETIC: 9>, 2132900915024: <ArtistRole.COSMETIC: 9>, 2132900915600: <ArtistRole.COSMETIC: 9>, 2132900627280: <ArtistRole.COSMETIC: 9>, 2132900916560: <ArtistRole.COSMETIC: 9>}, _original_state={'ax.title.text': '倾向得分分布', 'ax.title.fontsize': 13.0, 'ax.title.color': 'black', 'ax.title.fontweight': 'normal', 'ax.xlabel.text': 'Propensity Score', 'ax.xlabel.fontsize': 11.0, 'ax.xlabel.color': 'black', 'ax.ylabel.text': 'Density', 'ax.ylabel.fontsize': 11.0, 'ax.ylabel.color': 'black', 'ax.xlim': (np.float64(-0.02), np.float64(1.02)), 'ax.ylim': (np.float64(0.0), np.float64(3.9835051546391718)), 'ax.facecolor': (1.0, 1.0, 1.0, 1.0), 'ax.xtick_rotation': 0.0, 'ax.ytick_rotation': 0.0, 'ax.spines.left.visible': True, 'ax.spines.right.visible': False, 'ax.spines.bottom.visible': True, 'ax.spines.top.visible': False, 'ax.grid': False, 'ax.n_texts': 0, 'fig.figsize': (np.float64(8.0), np.float64(5.0)), 'fig.dpi': 150.0, 'fig.facecolor': (1.0, 1.0, 1.0, 1.0)}, _on_refresh_callbacks=[<function create_jupyter_panel.<locals>._live_refresh at 0x000001F09AF8A480>, <function create_jupyter_panel.<locals>._live_history_update at 0x000001F09B24CA40>, <function create_jupyter_panel.<locals>._live_code_update at 0x000001F09B044A40>], _redo_stack=[])

---
## 5. 合成控制法 (SC)

州 1 在 2005 年实施政策干预，使用 10 个捐赠州构建合成控制。

In [19]:
# 模拟合成控制数据：11 个州，20 个时期
n_states, n_periods = 11, 20
states = np.repeat(np.arange(1, n_states + 1), n_periods)
time_periods = np.tile(np.arange(2000, 2000 + n_periods), n_states)

# 每个州有基线趋势 + 州固定截距
state_intercepts = np.repeat(np.random.normal(50, 5, n_states), n_periods)
common_trend = np.tile(np.linspace(0, 10, n_periods), n_states)
noise = np.random.normal(0, 1, n_states * n_periods)

gdp = state_intercepts + common_trend + noise

# 为州 1 在 2005 年之后添加处理效应（效应 = +5）
treatment_effect = 5.0 * ((states == 1) & (time_periods >= 2005)).astype(float)
gdp += treatment_effect

df_synth = pd.DataFrame({
    'state': states, 'year': time_periods, 'gdp': gdp
})
df_synth.head()

   state  year        gdp
0      1  2000  47.983380
1      1  2001  49.634079
2      1  2002  48.875418
3      1  2003  50.008466
4      1  2004  49.088300

In [20]:
# 经典合成控制法
sc_result = sp.synth(
    df_synth,
    outcome='gdp', unit='state', time='year',
    treated_unit=1, treatment_time=2005
)
sc_result

In [21]:
# 绘图：处理单元 vs 合成控制轨迹
fig, ax = sp.synthplot(sc_result, type='trajectory',
                       title='合成控制：州 1 对比合成单元')
sp.interactive(fig)

HBox(children=(VBox(children=(Image(value=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x03\xda\x00\x00\x02}\x…

FigureEditor(fig=<Figure size 1500x975 with 1 Axes>, protect_data=True, edits=[], artist_roles={2132904043888: <ArtistRole.LABEL: 5>, 2132904050176: <ArtistRole.LABEL: 5>, 2132904046912: <ArtistRole.LABEL: 5>, 2132904049840: <ArtistRole.SPINE: 8>, 2132904035344: <ArtistRole.SPINE: 8>, 2132904043168: <ArtistRole.SPINE: 8>, 2132904049792: <ArtistRole.SPINE: 8>, 2132904001712: <ArtistRole.LEGEND: 7>, 2132906607104: <ArtistRole.DATA: 1>, 2132906616656: <ArtistRole.DATA: 1>, 2132904138928: <ArtistRole.REFERENCE: 4>, 2132904014000: <ArtistRole.CI: 3>}, _original_state={'ax.title.text': '合成控制：州 1 对比合成单元', 'ax.title.fontsize': 13.0, 'ax.title.color': 'black', 'ax.title.fontweight': 'normal', 'ax.xlabel.text': 'Time', 'ax.xlabel.fontsize': 11.0, 'ax.xlabel.color': 'black', 'ax.ylabel.text': 'Outcome', 'ax.ylabel.fontsize': 11.0, 'ax.ylabel.color': 'black', 'ax.xlim': (np.float64(1999.05), np.float64(2019.95)), 'ax.ylim': (np.float64(47.12487078585494), np.float64(66.01208356282729)), 'ax.facecolor': (1.0, 1.0, 1.0, 1.0), 'ax.xtick_rotation': 0.0, 'ax.ytick_rotation': 0.0, 'ax.spines.left.visible': True, 'ax.spines.right.visible': False, 'ax.spines.bottom.visible': True, 'ax.spines.top.visible': False, 'ax.grid': False, 'ax.line0.color': '#2C3E50', 'ax.line0.linewidth': 2.2, 'ax.line0.linestyle': '-', 'ax.line0.alpha': None, 'ax.line0.marker': 'None', 'ax.line1.color': '#E74C3C', 'ax.line1.linewidth': 2.2, 'ax.line1.linestyle': '--', 'ax.line1.alpha': None, 'ax.line1.marker': 'None', 'ax.line2.color': '#95A5A6', 'ax.line2.linewidth': 1.2, 'ax.line2.linestyle': ':', 'ax.line2.alpha': 0.8, 'ax.line2.marker': 'None', 'ax.coll0.alpha': 0.12, 'ax.coll0.facecolors': array([[0.90588235, 0.29803922, 0.23529412, 0.12      ]]), 'ax.n_texts': 0, 'fig.figsize': (np.float64(10.0), np.float64(6.5)), 'fig.dpi': 150.0, 'fig.facecolor': (1.0, 1.0, 1.0, 1.0)}, _on_refresh_callbacks=[<function create_jupyter_panel.<locals>._live_refresh at 0x000001F09B0536A0>, <function create_jupyter_panel.<locals>._live_history_update at 0x000001F09B6414E0>, <function create_jupyter_panel.<locals>._live_code_update at 0x000001F09B6423E0>], _redo_stack=[])

In [22]:
# 绘图：处理效应差距随时间变化
fig, ax = sp.synthplot(sc_result, type='gap',
                       title='合成控制：处理效应差距（处理组 − 合成组）')
sp.interactive(fig)

HBox(children=(VBox(children=(Image(value=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x03\xd9\x00\x00\x01\xe…

FigureEditor(fig=<Figure size 1500x750 with 1 Axes>, protect_data=True, edits=[], artist_roles={2132910364752: <ArtistRole.LABEL: 5>, 2132910368928: <ArtistRole.LABEL: 5>, 2132910367200: <ArtistRole.LABEL: 5>, 2132910371424: <ArtistRole.SPINE: 8>, 2132910370608: <ArtistRole.SPINE: 8>, 2132910369984: <ArtistRole.SPINE: 8>, 2132910369744: <ArtistRole.SPINE: 8>, 2132907129792: <ArtistRole.DATA: 1>, 2132910372432: <ArtistRole.REFERENCE: 4>, 2132904620496: <ArtistRole.REFERENCE: 4>, 2132910365280: <ArtistRole.CI: 3>}, _original_state={'ax.title.text': '合成控制：处理效应差距（处理组 − 合成组）', 'ax.title.fontsize': 13.0, 'ax.title.color': 'black', 'ax.title.fontweight': 'normal', 'ax.xlabel.text': 'Time', 'ax.xlabel.fontsize': 11.0, 'ax.xlabel.color': 'black', 'ax.ylabel.text': 'Gap (Treated − Synthetic)', 'ax.ylabel.fontsize': 11.0, 'ax.ylabel.color': 'black', 'ax.xlim': (np.float64(1999.05), np.float64(2019.95)), 'ax.ylim': (np.float64(-1.2140147429398183), np.float64(8.846970513929614)), 'ax.facecolor': (1.0, 1.0, 1.0, 1.0), 'ax.xtick_rotation': 0.0, 'ax.ytick_rotation': 0.0, 'ax.spines.left.visible': True, 'ax.spines.right.visible': False, 'ax.spines.bottom.visible': True, 'ax.spines.top.visible': False, 'ax.grid': False, 'ax.line0.color': '#2C3E50', 'ax.line0.linewidth': 2.0, 'ax.line0.linestyle': '-', 'ax.line0.alpha': None, 'ax.line0.marker': 'None', 'ax.line1.color': 'gray', 'ax.line1.linewidth': 0.8, 'ax.line1.linestyle': '--', 'ax.line1.alpha': None, 'ax.line1.marker': 'None', 'ax.line2.color': '#95A5A6', 'ax.line2.linewidth': 1.2, 'ax.line2.linestyle': ':', 'ax.line2.alpha': 0.8, 'ax.line2.marker': 'None', 'ax.coll0.alpha': 0.12, 'ax.coll0.facecolors': array([[0.20392157, 0.59607843, 0.85882353, 0.12      ]]), 'ax.n_texts': 0, 'fig.figsize': (np.float64(10.0), np.float64(5.0)), 'fig.dpi': 150.0, 'fig.facecolor': (1.0, 1.0, 1.0, 1.0)}, _on_refresh_callbacks=[<function create_jupyter_panel.<locals>._live_refresh at 0x000001F09B641EE0>, <function create_jupyter_panel.<locals>._live_history_update at 0x000001F09B747CE0>, <function create_jupyter_panel.<locals>._live_code_update at 0x000001F09B980C20>], _redo_stack=[])

In [23]:
# 绘图：捐赠州权重
fig, ax = sp.synthplot(sc_result, type='weights',
                       title='合成控制：捐赠州权重')
sp.interactive(fig)

HBox(children=(VBox(children=(Image(value=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x03\x12\x00\x00\x01\xe…

FigureEditor(fig=<Figure size 1200x750 with 1 Axes>, protect_data=True, edits=[], artist_roles={2132911822496: <ArtistRole.LABEL: 5>, 2132911827008: <ArtistRole.LABEL: 5>, 2132911824992: <ArtistRole.LABEL: 5>, 2132911829504: <ArtistRole.SPINE: 8>, 2132911828544: <ArtistRole.SPINE: 8>, 2132911828640: <ArtistRole.SPINE: 8>, 2132911828448: <ArtistRole.SPINE: 8>, 2132911830656: <ArtistRole.REFERENCE: 4>, 2132911539984: <ArtistRole.COSMETIC: 9>, 2132911540512: <ArtistRole.COSMETIC: 9>, 2132911538352: <ArtistRole.COSMETIC: 9>, 2132910914832: <ArtistRole.COSMETIC: 9>}, _original_state={'ax.title.text': '合成控制：捐赠州权重', 'ax.title.fontsize': 13.0, 'ax.title.color': 'black', 'ax.title.fontweight': 'normal', 'ax.xlabel.text': 'Weight', 'ax.xlabel.fontsize': 11.0, 'ax.xlabel.color': 'black', 'ax.ylabel.text': '', 'ax.ylabel.fontsize': 11.0, 'ax.ylabel.color': 'black', 'ax.xlim': (np.float64(0.0), np.float64(0.4642936592746855)), 'ax.ylim': (np.float64(-0.5900000000000001), np.float64(3.5900000000000003)), 'ax.facecolor': (1.0, 1.0, 1.0, 1.0), 'ax.xtick_rotation': 0.0, 'ax.ytick_rotation': 0.0, 'ax.spines.left.visible': True, 'ax.spines.right.visible': False, 'ax.spines.bottom.visible': True, 'ax.spines.top.visible': False, 'ax.grid': False, 'ax.line0.color': 'gray', 'ax.line0.linewidth': 0.5, 'ax.line0.linestyle': '-', 'ax.line0.alpha': None, 'ax.line0.marker': 'None', 'ax.n_texts': 0, 'fig.figsize': (np.float64(8.0), np.float64(5.0)), 'fig.dpi': 150.0, 'fig.facecolor': (1.0, 1.0, 1.0, 1.0)}, _on_refresh_callbacks=[<function create_jupyter_panel.<locals>._live_refresh at 0x000001F09B981300>, <function create_jupyter_panel.<locals>._live_history_update at 0x000001F09B980A40>, <function create_jupyter_panel.<locals>._live_code_update at 0x000001F09BA5B740>], _redo_stack=[])

In [24]:
# 绘图：安慰剂检验（空间维度）
fig, ax = sp.synthplot(sc_result, type='placebo',
                       title='合成控制：空间安慰剂检验')
sp.interactive(fig)

HBox(children=(VBox(children=(Image(value=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x03q\x00\x00\x02K\x08\…

FigureEditor(fig=<Figure size 1350x900 with 1 Axes>, protect_data=True, edits=[], artist_roles={2132914880192: <ArtistRole.LABEL: 5>, 2132915115632: <ArtistRole.LABEL: 5>, 2132915113328: <ArtistRole.LABEL: 5>, 2132915118128: <ArtistRole.SPINE: 8>, 2132915117312: <ArtistRole.SPINE: 8>, 2132915116784: <ArtistRole.SPINE: 8>, 2132915116112: <ArtistRole.SPINE: 8>, 2132914874624: <ArtistRole.LEGEND: 7>, 2132914865792: <ArtistRole.REFERENCE: 4>, 2132915123360: <ArtistRole.ANNOTATION: 6>, 2132914585232: <ArtistRole.COSMETIC: 9>, 2132907046000: <ArtistRole.COSMETIC: 9>, 2132910257696: <ArtistRole.COSMETIC: 9>, 2132914582640: <ArtistRole.COSMETIC: 9>, 2132914581440: <ArtistRole.COSMETIC: 9>, 2132914581056: <ArtistRole.COSMETIC: 9>, 2132914877696: <ArtistRole.COSMETIC: 9>, 2132914579952: <ArtistRole.COSMETIC: 9>}, _original_state={'ax.title.text': '合成控制：空间安慰剂检验', 'ax.title.fontsize': 13.0, 'ax.title.color': 'black', 'ax.title.fontweight': 'normal', 'ax.xlabel.text': 'ATT', 'ax.xlabel.fontsize': 11.0, 'ax.xlabel.color': 'black', 'ax.ylabel.text': 'Count', 'ax.ylabel.fontsize': 11.0, 'ax.ylabel.color': 'black', 'ax.xlim': (np.float64(-1.789816242511311), np.float64(6.638496734917001)), 'ax.ylim': (np.float64(0.0), np.float64(5.25)), 'ax.facecolor': (1.0, 1.0, 1.0, 1.0), 'ax.xtick_rotation': 0.0, 'ax.ytick_rotation': 0.0, 'ax.spines.left.visible': True, 'ax.spines.right.visible': False, 'ax.spines.bottom.visible': True, 'ax.spines.top.visible': False, 'ax.grid': False, 'ax.line0.color': '#E74C3C', 'ax.line0.linewidth': 2.5, 'ax.line0.linestyle': '--', 'ax.line0.alpha': None, 'ax.line0.marker': 'None', 'ax.n_texts': 1, 'fig.figsize': (np.float64(9.0), np.float64(6.0)), 'fig.dpi': 150.0, 'fig.facecolor': (1.0, 1.0, 1.0, 1.0)}, _on_refresh_callbacks=[<function create_jupyter_panel.<locals>._live_refresh at 0x000001F09BC37B00>, <function create_jupyter_panel.<locals>._live_history_update at 0x000001F09BF55300>, <function create_jupyter_panel.<locals>._live_code_update at 0x000001F09BF562A0>], _redo_stack=[])

---
## 6. 断点回归设计 (RDD)

基于考试分数 60 分断点的奖学金资格评估。

In [25]:
# 模拟 RDD 数据：分数断点在 60 分
n_rd = 2000
score = np.random.normal(60, 15, n_rd)  # 驱动变量，断点在 60 分
above_cutoff = (score >= 60).astype(int)

# 结果变量：GPA 在断点处跳跃（处理效应 = 0.4）
gpa = 2.5 + 0.02 * score + 0.4 * above_cutoff + np.random.normal(0, 0.3, n_rd)

df_rd = pd.DataFrame({
    'gpa': gpa, 'test_score': score, 'scholarship': above_cutoff
})
df_rd.head()

        gpa  test_score  scholarship
0  4.704528   79.379964            1
1  3.760986   53.293551            0
2  4.232309   83.322604            1
3  4.320970   62.941639            1
4  4.392721   90.379263            1

In [26]:
# 精确断点回归估计
rd_result = sp.rdrobust(
    df_rd, y='gpa', x='test_score', c=60
)
rd_result

In [27]:
# 绘图：RD 散点图（含多项式拟合和置信区间阴影）
fig, ax = sp.rdplot(
    df_rd, y='gpa', x='test_score', c=60,
    nbins=40, ci_level=0.95, shade_ci=True,
    show_bw=True,
    title='断点回归：奖学金对 GPA 的影响',
)
sp.interactive(fig)

HBox(children=(VBox(children=(Image(value=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x03\xda\x00\x00\x02\xa…

FigureEditor(fig=<Figure size 1500x1050 with 1 Axes>, protect_data=True, edits=[], artist_roles={2132917802512: <ArtistRole.LABEL: 5>, 2132917809136: <ArtistRole.LABEL: 5>, 2132917807408: <ArtistRole.LABEL: 5>, 2132917811152: <ArtistRole.SPINE: 8>, 2132917810960: <ArtistRole.SPINE: 8>, 2132917810528: <ArtistRole.SPINE: 8>, 2132917810048: <ArtistRole.SPINE: 8>, 2132920202736: <ArtistRole.LEGEND: 7>, 2132917191600: <ArtistRole.REFERENCE: 4>, 2132917492608: <ArtistRole.REFERENCE: 4>, 2132917802944: <ArtistRole.REFERENCE: 4>, 2132917205232: <ArtistRole.REFERENCE: 4>, 2132917193040: <ArtistRole.REFERENCE: 4>, 2132917204896: <ArtistRole.REFERENCE: 4>, 2132920492944: <ArtistRole.DATA: 1>, 2132920491936: <ArtistRole.DATA: 1>, 2132917126976: <ArtistRole.REFERENCE: 4>, 2132917491024: <ArtistRole.CI: 3>, 2132920193376: <ArtistRole.CI: 3>, 2132917488672: <ArtistRole.CI: 3>, 2132917199040: <ArtistRole.CI: 3>, 2132917495920: <ArtistRole.COSMETIC: 9>}, _original_state={'ax.title.text': '断点回归：奖学金对 GPA 的影响', 'ax.title.fontsize': 13.0, 'ax.title.color': 'black', 'ax.title.fontweight': 'normal', 'ax.xlabel.text': 'test_score', 'ax.xlabel.fontsize': 11.0, 'ax.xlabel.color': 'black', 'ax.ylabel.text': 'gpa', 'ax.ylabel.fontsize': 11.0, 'ax.ylabel.color': 'black', 'ax.xlim': (np.float64(0.0798728508686235), np.float64(112.14412014740388)), 'ax.ylim': (np.float64(1.64445715959014), np.float64(5.696197877359477)), 'ax.facecolor': (1.0, 1.0, 1.0, 1.0), 'ax.xtick_rotation': 0.0, 'ax.ytick_rotation': 0.0, 'ax.spines.left.visible': True, 'ax.spines.right.visible': False, 'ax.spines.bottom.visible': True, 'ax.spines.top.visible': False, 'ax.grid': False, 'ax.line0.color': '#2C3E50', 'ax.line0.linewidth': 0.8, 'ax.line0.linestyle': 'None', 'ax.line0.alpha': 0.7, 'ax.line0.marker': 'o', 'ax.line1.color': '#2C3E50', 'ax.line1.linewidth': 0.8, 'ax.line1.linestyle': 'None', 'ax.line1.alpha': 0.7, 'ax.line1.marker': '_', 'ax.line2.color': '#2C3E50', 'ax.line2.linewidth': 0.8, 'ax.line2.linestyle': 'None', 'ax.line2.alpha': 0.7, 'ax.line2.marker': '_', 'ax.line3.color': '#2C3E50', 'ax.line3.linewidth': 0.8, 'ax.line3.linestyle': 'None', 'ax.line3.alpha': 0.7, 'ax.line3.marker': 'o', 'ax.line4.color': '#2C3E50', 'ax.line4.linewidth': 0.8, 'ax.line4.linestyle': 'None', 'ax.line4.alpha': 0.7, 'ax.line4.marker': '_', 'ax.line5.color': '#2C3E50', 'ax.line5.linewidth': 0.8, 'ax.line5.linestyle': 'None', 'ax.line5.alpha': 0.7, 'ax.line5.marker': '_', 'ax.line6.color': '#E74C3C', 'ax.line6.linewidth': 1.5, 'ax.line6.linestyle': '-', 'ax.line6.alpha': None, 'ax.line6.marker': 'None', 'ax.line7.color': '#3498DB', 'ax.line7.linewidth': 1.5, 'ax.line7.linestyle': '-', 'ax.line7.alpha': None, 'ax.line7.marker': 'None', 'ax.line8.color': 'gray', 'ax.line8.linewidth': 0.8, 'ax.line8.linestyle': '--', 'ax.line8.alpha': 0.7, 'ax.line8.marker': 'None', 'ax.coll0.alpha': 0.12, 'ax.coll0.facecolors': array([[0.90588235, 0.29803922, 0.23529412, 0.12      ]]), 'ax.coll1.alpha': 0.12, 'ax.coll1.facecolors': array([[0.20392157, 0.59607843, 0.85882353, 0.12      ]]), 'ax.coll2.alpha': 0.7, 'ax.coll2.facecolors': array([], shape=(0, 4), dtype=float64), 'ax.coll3.alpha': 0.7, 'ax.coll3.facecolors': array([], shape=(0, 4), dtype=float64), 'ax.n_texts': 0, 'fig.figsize': (np.float64(10.0), np.float64(7.0)), 'fig.dpi': 150.0, 'fig.facecolor': (1.0, 1.0, 1.0, 1.0)}, _on_refresh_callbacks=[<function create_jupyter_panel.<locals>._live_refresh at 0x000001F09BF68B80>, <function create_jupyter_panel.<locals>._live_history_update at 0x000001F09BF69BC0>, <function create_jupyter_panel.<locals>._live_code_update at 0x000001F09BF6B600>], _redo_stack=[])

In [28]:
# 绘图：密度检验（McCrary 式）—— 检查是否存在操纵
fig, ax = sp.rdplotdensity(
    df_rd, x='test_score', c=60,
    hist=True, nbins=40, ci_level=0.95,
    title='断点回归：断点处驱动变量密度',
)
sp.interactive(fig)

HBox(children=(VBox(children=(Image(value=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x03\xda\x00\x00\x02\xa…

FigureEditor(fig=<Figure size 1500x1050 with 1 Axes>, protect_data=True, edits=[], artist_roles={2132920847344: <ArtistRole.LABEL: 5>, 2132924124528: <ArtistRole.LABEL: 5>, 2132924128128: <ArtistRole.LABEL: 5>, 2132924130864: <ArtistRole.SPINE: 8>, 2132924122128: <ArtistRole.SPINE: 8>, 2132924122416: <ArtistRole.SPINE: 8>, 2132924123136: <ArtistRole.SPINE: 8>, 2132920904992: <ArtistRole.LEGEND: 7>, 2132917134800: <ArtistRole.REFERENCE: 4>, 2132925222304: <ArtistRole.REFERENCE: 4>, 2132924959536: <ArtistRole.REFERENCE: 4>, 2132924466432: <ArtistRole.CI: 3>, 2132925222688: <ArtistRole.CI: 3>, 2132924466096: <ArtistRole.COSMETIC: 9>, 2132920849744: <ArtistRole.COSMETIC: 9>, 2132924474160: <ArtistRole.COSMETIC: 9>, 2132924474736: <ArtistRole.COSMETIC: 9>, 2132924475312: <ArtistRole.COSMETIC: 9>, 2132920846768: <ArtistRole.COSMETIC: 9>, 2132924476368: <ArtistRole.COSMETIC: 9>, 2132924476944: <ArtistRole.COSMETIC: 9>, 2132924477520: <ArtistRole.COSMETIC: 9>, 2132924478000: <ArtistRole.COSMETIC: 9>, 2132924478528: <ArtistRole.COSMETIC: 9>, 2132924479104: <ArtistRole.COSMETIC: 9>, 2132924479632: <ArtistRole.COSMETIC: 9>, 2132924480208: <ArtistRole.COSMETIC: 9>, 2132924480688: <ArtistRole.COSMETIC: 9>, 2132924481168: <ArtistRole.COSMETIC: 9>, 2132924711184: <ArtistRole.COSMETIC: 9>, 2132924474448: <ArtistRole.COSMETIC: 9>, 2132924712240: <ArtistRole.COSMETIC: 9>, 2132924712816: <ArtistRole.COSMETIC: 9>, 2132924713392: <ArtistRole.COSMETIC: 9>, 2132924713968: <ArtistRole.COSMETIC: 9>, 2132924714544: <ArtistRole.COSMETIC: 9>, 2132924715072: <ArtistRole.COSMETIC: 9>, 2132920907104: <ArtistRole.COSMETIC: 9>, 2132924716080: <ArtistRole.COSMETIC: 9>, 2132924716656: <ArtistRole.COSMETIC: 9>, 2132924717184: <ArtistRole.COSMETIC: 9>, 2132924717712: <ArtistRole.COSMETIC: 9>, 2132924718288: <ArtistRole.COSMETIC: 9>, 2132924718576: <ArtistRole.COSMETIC: 9>, 2132924719344: <ArtistRole.COSMETIC: 9>, 2132924719824: <ArtistRole.COSMETIC: 9>, 2132924720400: <ArtistRole.COSMETIC: 9>, 2132924720976: <ArtistRole.COSMETIC: 9>, 2132924721504: <ArtistRole.COSMETIC: 9>, 2132924721984: <ArtistRole.COSMETIC: 9>, 2132920895728: <ArtistRole.COSMETIC: 9>, 2132924723040: <ArtistRole.COSMETIC: 9>, 2132917129520: <ArtistRole.COSMETIC: 9>, 2132924466144: <ArtistRole.COSMETIC: 9>, 2132920894720: <ArtistRole.COSMETIC: 9>, 2132924724576: <ArtistRole.COSMETIC: 9>, 2132924725152: <ArtistRole.COSMETIC: 9>, 2132924725680: <ArtistRole.COSMETIC: 9>, 2132924726208: <ArtistRole.COSMETIC: 9>, 2132917134464: <ArtistRole.COSMETIC: 9>, 2132924726880: <ArtistRole.COSMETIC: 9>, 2132924957328: <ArtistRole.COSMETIC: 9>, 2132924712528: <ArtistRole.COSMETIC: 9>, 2132924958384: <ArtistRole.COSMETIC: 9>, 2132924958912: <ArtistRole.COSMETIC: 9>, 2132920849024: <ArtistRole.COSMETIC: 9>, 2132920896304: <ArtistRole.COSMETIC: 9>, 2132924960544: <ArtistRole.COSMETIC: 9>, 2132924961120: <ArtistRole.COSMETIC: 9>, 2132924961648: <ArtistRole.COSMETIC: 9>, 2132924712912: <ArtistRole.COSMETIC: 9>, 2132924962704: <ArtistRole.COSMETIC: 9>, 2132924963232: <ArtistRole.COSMETIC: 9>, 2132924963760: <ArtistRole.COSMETIC: 9>, 2132924964336: <ArtistRole.COSMETIC: 9>, 2132924964864: <ArtistRole.COSMETIC: 9>, 2132924130624: <ArtistRole.COSMETIC: 9>, 2132917199424: <ArtistRole.COSMETIC: 9>, 2132924966160: <ArtistRole.COSMETIC: 9>, 2132924966736: <ArtistRole.COSMETIC: 9>, 2132924713488: <ArtistRole.COSMETIC: 9>, 2132920848400: <ArtistRole.COSMETIC: 9>, 2132924968368: <ArtistRole.COSMETIC: 9>, 2132924968944: <ArtistRole.COSMETIC: 9>, 2132924969472: <ArtistRole.COSMETIC: 9>, 2132924478816: <ArtistRole.COSMETIC: 9>, 2132924479296: <ArtistRole.COSMETIC: 9>, 2132924971056: <ArtistRole.COSMETIC: 9>, 2132924479728: <ArtistRole.COSMETIC: 9>, 2132924972112: <ArtistRole.COSMETIC: 9>, 2132924481456: <ArtistRole.COSMETIC: 9>, 2132924972832: <ArtistRole.COSMETIC: 9>, 2132925219616: <ArtistRole.COSMETIC: 9>}, _original_state={'ax.title.text': '断点回归：断点处驱动变量密度', 'ax.title.fontsize': 13.0, 'ax.title.color': 'black', 'ax.title.fontweight': 'normal', 'ax.xlabel.text': 'test_score', 'ax.xlabel.fontsize': 11.0, 'ax.xlabel.color': 'black', 'ax.ylabel.text': 'Density', 'ax.ylabel.fontsize': 11.0, 'ax.ylabel.color': 'black', 'ax.xlim': (np.float64(0.0798728508686235), np.float64(112.14412014740388)), 'ax.ylim': (np.float64(0.0), np.float64(0.06191045852950382)), 'ax.facecolor': (1.0, 1.0, 1.0, 1.0), 'ax.xtick_rotation': 0.0, 'ax.ytick_rotation': 0.0, 'ax.spines.left.visible': True, 'ax.spines.right.visible': False, 'ax.spines.bottom.visible': True, 'ax.spines.top.visible': False, 'ax.grid': False, 'ax.line0.color': '#E74C3C', 'ax.line0.linewidth': 2.0, 'ax.line0.linestyle': '-', 'ax.line0.alpha': None, 'ax.line0.marker': 'None', 'ax.line1.color': '#3498DB', 'ax.line1.linewidth': 2.0, 'ax.line1.linestyle': '-', 'ax.line1.alpha': None, 'ax.line1.marker': 'None', 'ax.line2.color': 'gray', 'ax.line2.linewidth': 1.0, 'ax.line2.linestyle': '--', 'ax.line2.alpha': 0.7, 'ax.line2.marker': 'None', 'ax.coll0.alpha': 0.15, 'ax.coll0.facecolors': array([[0.90588235, 0.29803922, 0.23529412, 0.15      ]]), 'ax.coll1.alpha': 0.15, 'ax.coll1.facecolors': array([[0.20392157, 0.59607843, 0.85882353, 0.15      ]]), 'ax.n_texts': 0, 'fig.figsize': (np.float64(10.0), np.float64(7.0)), 'fig.dpi': 150.0, 'fig.facecolor': (1.0, 1.0, 1.0, 1.0)}, _on_refresh_callbacks=[<function create_jupyter_panel.<locals>._live_refresh at 0x000001F09C412F20>, <function create_jupyter_panel.<locals>._live_history_update at 0x000001F09C765800>, <function create_jupyter_panel.<locals>._live_code_update at 0x000001F09C7647C0>], _redo_stack=[])

In [29]:
# 绘图：带宽敏感性 —— 不同带宽下 RD 估计的稳健性
_ = sp.rdbwsensitivity(df_rd, y='gpa', x='test_score', c=60, n_grid=20)
fig = plt.gcf()
sp.interactive(fig)

HBox(children=(VBox(children=(Image(value=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x03\xda\x00\x00\x02L\x…

FigureEditor(fig=<Figure size 1500x900 with 1 Axes>, protect_data=True, edits=[], artist_roles={2132928705312: <ArtistRole.LABEL: 5>, 2132928696960: <ArtistRole.LABEL: 5>, 2132928699504: <ArtistRole.LABEL: 5>, 2132928694320: <ArtistRole.SPINE: 8>, 2132928694368: <ArtistRole.SPINE: 8>, 2132928695088: <ArtistRole.SPINE: 8>, 2132928695760: <ArtistRole.SPINE: 8>, 2132929017328: <ArtistRole.LEGEND: 7>, 2132925531872: <ArtistRole.DATA: 1>, 2132925544976: <ArtistRole.REFERENCE: 4>, 2132929009312: <ArtistRole.REFERENCE: 4>, 2132929011328: <ArtistRole.REFERENCE: 4>, 2132925530192: <ArtistRole.REFERENCE: 4>, 2132929010464: <ArtistRole.CI: 3>}, _original_state={'ax.title.text': 'Bandwidth Sensitivity', 'ax.title.fontsize': 13.0, 'ax.title.color': 'black', 'ax.title.fontweight': 'normal', 'ax.xlabel.text': 'Bandwidth', 'ax.xlabel.fontsize': 11.0, 'ax.xlabel.color': 'black', 'ax.ylabel.text': 'RD Estimate', 'ax.ylabel.fontsize': 11.0, 'ax.ylabel.color': 'black', 'ax.xlim': (np.float64(1.274459825), np.float64(6.222362675)), 'ax.ylim': (np.float64(-0.034920611911104654), np.float64(0.7333328501331978)), 'ax.facecolor': (1.0, 1.0, 1.0, 1.0), 'ax.xtick_rotation': 0.0, 'ax.ytick_rotation': 0.0, 'ax.spines.left.visible': True, 'ax.spines.right.visible': False, 'ax.spines.bottom.visible': True, 'ax.spines.top.visible': False, 'ax.grid': False, 'ax.line0.color': '#2C3E50', 'ax.line0.linewidth': 1.0, 'ax.line0.linestyle': '-', 'ax.line0.alpha': 0.8, 'ax.line0.marker': 'o', 'ax.line1.color': '#2C3E50', 'ax.line1.linewidth': 1.0, 'ax.line1.linestyle': 'None', 'ax.line1.alpha': 0.8, 'ax.line1.marker': '_', 'ax.line2.color': '#2C3E50', 'ax.line2.linewidth': 1.0, 'ax.line2.linestyle': 'None', 'ax.line2.alpha': 0.8, 'ax.line2.marker': '_', 'ax.line3.color': 'gray', 'ax.line3.linewidth': 0.8, 'ax.line3.linestyle': '--', 'ax.line3.alpha': None, 'ax.line3.marker': 'None', 'ax.line4.color': '#E74C3C', 'ax.line4.linewidth': 0.8, 'ax.line4.linestyle': '--', 'ax.line4.alpha': 0.7, 'ax.line4.marker': 'None', 'ax.coll0.alpha': 0.8, 'ax.coll0.facecolors': array([], shape=(0, 4), dtype=float64), 'ax.n_texts': 0, 'fig.figsize': (np.float64(10.0), np.float64(6.0)), 'fig.dpi': 150.0, 'fig.facecolor': (1.0, 1.0, 1.0, 1.0)}, _on_refresh_callbacks=[<function create_jupyter_panel.<locals>._live_refresh at 0x000001F09C802DE0>, <function create_jupyter_panel.<locals>._live_history_update at 0x000001F09CB89D00>, <function create_jupyter_panel.<locals>._live_code_update at 0x000001F09CB8AC00>], _redo_stack=[])

---
## 7. 分箱散点图 (Binscatter)

非参数条件均值图 —— 应用微观经济学可视化的常用工具。

In [30]:
# 分箱散点图：工资 vs 教育年限（来自 IV 数据），带置信区间
fig, ax, _ = sp.binscatter(
    df_iv, y='wage', x='education',
    n_bins=30, ci=True, ci_level=0.95,
    fit='linear',
    figsize=(9, 6),
)
ax.set_title('分箱散点图：工资与教育年限', fontsize=13)
ax.set_xlabel('教育年限', fontsize=11)
ax.set_ylabel('小时工资（美元）', fontsize=11)
sp.interactive(fig)

HBox(children=(VBox(children=(Image(value=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x03v\x00\x00\x02a\x08\…

FigureEditor(fig=<Figure size 1350x900 with 1 Axes>, protect_data=True, edits=[], artist_roles={2132932910336: <ArtistRole.LABEL: 5>, 2132932917920: <ArtistRole.LABEL: 5>, 2132932915904: <ArtistRole.LABEL: 5>, 2132933166000: <ArtistRole.SPINE: 8>, 2132933166336: <ArtistRole.SPINE: 8>, 2132933165472: <ArtistRole.SPINE: 8>, 2132932919264: <ArtistRole.SPINE: 8>, 2132929739856: <ArtistRole.REFERENCE: 4>, 2132932641376: <ArtistRole.REFERENCE: 4>, 2132929738272: <ArtistRole.DATA: 1>, 2132933179104: <ArtistRole.DATA: 1>, 2132932651936: <ArtistRole.CI: 3>}, _original_state={'ax.title.text': '分箱散点图：工资与教育年限', 'ax.title.fontsize': 13.0, 'ax.title.color': 'black', 'ax.title.fontweight': 'normal', 'ax.xlabel.text': '教育年限', 'ax.xlabel.fontsize': 11.0, 'ax.xlabel.color': 'black', 'ax.ylabel.text': '小时工资（美元）', 'ax.ylabel.fontsize': 11.0, 'ax.ylabel.color': 'black', 'ax.xlim': (np.float64(7.23083792908043), np.float64(16.794586435945824)), 'ax.ylim': (np.float64(17.30389032141836), np.float64(27.374847689259703)), 'ax.facecolor': (1.0, 1.0, 1.0, 1.0), 'ax.xtick_rotation': 0.0, 'ax.ytick_rotation': 0.0, 'ax.spines.left.visible': True, 'ax.spines.right.visible': False, 'ax.spines.bottom.visible': True, 'ax.spines.top.visible': False, 'ax.grid': False, 'ax.line0.color': '#2C3E50', 'ax.line0.linewidth': 0.8, 'ax.line0.linestyle': 'None', 'ax.line0.alpha': 0.6, 'ax.line0.marker': '_', 'ax.line1.color': '#2C3E50', 'ax.line1.linewidth': 0.8, 'ax.line1.linestyle': 'None', 'ax.line1.alpha': 0.6, 'ax.line1.marker': '_', 'ax.line2.color': '#2C3E50', 'ax.line2.linewidth': 1.5, 'ax.line2.linestyle': '-', 'ax.line2.alpha': 0.8, 'ax.line2.marker': 'None', 'ax.coll0.alpha': 0.85, 'ax.coll0.facecolors': array([[0.17254902, 0.24313725, 0.31372549, 0.85      ]]), 'ax.coll1.alpha': 0.6, 'ax.coll1.facecolors': array([], shape=(0, 4), dtype=float64), 'ax.n_texts': 0, 'fig.figsize': (np.float64(9.0), np.float64(6.0)), 'fig.dpi': 150.0, 'fig.facecolor': (1.0, 1.0, 1.0, 1.0)}, _on_refresh_callbacks=[<function create_jupyter_panel.<locals>._live_refresh at 0x000001F09C7ABE20>, <function create_jupyter_panel.<locals>._live_history_update at 0x000001F09CEDDF80>, <function create_jupyter_panel.<locals>._live_code_update at 0x000001F09CEDEE80>], _redo_stack=[])

In [31]:
# 分箱散点图：工资 vs 教育年限，控制工作经验（二次拟合）
fig, ax, _ = sp.binscatter(
    df_iv, y='wage', x='education',
    controls=['experience'],
    n_bins=25, ci=True,
    fit='quadratic',
    figsize=(9, 6),
)
ax.set_title('分箱散点图：工资与教育年限\n（控制工作经验，二次拟合）', fontsize=12)
sp.interactive(fig)

HBox(children=(VBox(children=(Image(value=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x03v\x00\x00\x02r\x08\…

FigureEditor(fig=<Figure size 1350x900 with 1 Axes>, protect_data=True, edits=[], artist_roles={2132934142352: <ArtistRole.LABEL: 5>, 2132934146960: <ArtistRole.LABEL: 5>, 2132934145328: <ArtistRole.LABEL: 5>, 2132936670288: <ArtistRole.SPINE: 8>, 2132936655264: <ArtistRole.SPINE: 8>, 2132936654928: <ArtistRole.SPINE: 8>, 2132934147728: <ArtistRole.SPINE: 8>, 2132933177424: <ArtistRole.REFERENCE: 4>, 2132929735968: <ArtistRole.REFERENCE: 4>, 2132933425680: <ArtistRole.DATA: 1>, 2132933891120: <ArtistRole.DATA: 1>, 2132933887088: <ArtistRole.CI: 3>}, _original_state={'ax.title.text': '分箱散点图：工资与教育年限\n（控制工作经验，二次拟合）', 'ax.title.fontsize': 12.0, 'ax.title.color': 'black', 'ax.title.fontweight': 'normal', 'ax.xlabel.text': 'education', 'ax.xlabel.fontsize': 11.0, 'ax.xlabel.color': 'black', 'ax.ylabel.text': 'wage', 'ax.ylabel.fontsize': 11.0, 'ax.ylabel.color': 'black', 'ax.xlim': (np.float64(7.391837015178976), np.float64(16.640096996074455)), 'ax.ylim': (np.float64(17.601764441716284), np.float64(26.941871372749723)), 'ax.facecolor': (1.0, 1.0, 1.0, 1.0), 'ax.xtick_rotation': 0.0, 'ax.ytick_rotation': 0.0, 'ax.spines.left.visible': True, 'ax.spines.right.visible': False, 'ax.spines.bottom.visible': True, 'ax.spines.top.visible': False, 'ax.grid': False, 'ax.line0.color': '#2C3E50', 'ax.line0.linewidth': 0.8, 'ax.line0.linestyle': 'None', 'ax.line0.alpha': 0.6, 'ax.line0.marker': '_', 'ax.line1.color': '#2C3E50', 'ax.line1.linewidth': 0.8, 'ax.line1.linestyle': 'None', 'ax.line1.alpha': 0.6, 'ax.line1.marker': '_', 'ax.line2.color': '#2C3E50', 'ax.line2.linewidth': 1.5, 'ax.line2.linestyle': '-', 'ax.line2.alpha': 0.8, 'ax.line2.marker': 'None', 'ax.coll0.alpha': 0.85, 'ax.coll0.facecolors': array([[0.17254902, 0.24313725, 0.31372549, 0.85      ]]), 'ax.coll1.alpha': 0.6, 'ax.coll1.facecolors': array([], shape=(0, 4), dtype=float64), 'ax.n_texts': 0, 'fig.figsize': (np.float64(9.0), np.float64(6.0)), 'fig.dpi': 150.0, 'fig.facecolor': (1.0, 1.0, 1.0, 1.0)}, _on_refresh_callbacks=[<function create_jupyter_panel.<locals>._live_refresh at 0x000001F09CBD4860>, <function create_jupyter_panel.<locals>._live_history_update at 0x000001F09D2559E0>, <function create_jupyter_panel.<locals>._live_code_update at 0x000001F09D2568E0>], _redo_stack=[])

In [32]:
# 按组分箱散点图：收入 vs 年龄，按处理状态分组
fig, ax, _ = sp.binscatter(
    df_match, y='earnings', x='age',
    by='treatment',
    n_bins=20, ci=True,
    fit='linear',
    figsize=(9, 6),
)
ax.set_title('分箱散点图：按处理状态分组的收入与年龄', fontsize=13)
ax.set_xlabel('年龄', fontsize=11)
ax.set_ylabel('收入（美元）', fontsize=11)
sp.interactive(fig)

HBox(children=(VBox(children=(Image(value=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x03w\x00\x00\x02`\x08\…

FigureEditor(fig=<Figure size 1350x900 with 1 Axes>, protect_data=True, edits=[], artist_roles={2132939972800: <ArtistRole.LABEL: 5>, 2132939980384: <ArtistRole.LABEL: 5>, 2132940204912: <ArtistRole.LABEL: 5>, 2132940204432: <ArtistRole.SPINE: 8>, 2132940195456: <ArtistRole.SPINE: 8>, 2132940194832: <ArtistRole.SPINE: 8>, 2132940194448: <ArtistRole.SPINE: 8>, 2132936990096: <ArtistRole.LEGEND: 7>, 2132940206880: <ArtistRole.REFERENCE: 4>, 2132933501600: <ArtistRole.REFERENCE: 4>, 2132936994224: <ArtistRole.DATA: 1>, 2132936985248: <ArtistRole.REFERENCE: 4>, 2132936984096: <ArtistRole.REFERENCE: 4>, 2132936930560: <ArtistRole.DATA: 1>, 2132937415072: <ArtistRole.DATA: 1>, 2132937409888: <ArtistRole.CI: 3>, 2132936992256: <ArtistRole.DATA: 1>, 2132936987552: <ArtistRole.CI: 3>}, _original_state={'ax.title.text': '分箱散点图：按处理状态分组的收入与年龄', 'ax.title.fontsize': 13.0, 'ax.title.color': 'black', 'ax.title.fontweight': 'normal', 'ax.xlabel.text': '年龄', 'ax.xlabel.fontsize': 11.0, 'ax.xlabel.color': 'black', 'ax.ylabel.text': '收入（美元）', 'ax.ylabel.fontsize': 11.0, 'ax.ylabel.color': 'black', 'ax.xlim': (np.float64(15.194039601853877), np.float64(53.695488158841044)), 'ax.ylim': (np.float64(44491.11862702388), np.float64(56187.279431778414)), 'ax.facecolor': (1.0, 1.0, 1.0, 1.0), 'ax.xtick_rotation': 0.0, 'ax.ytick_rotation': 0.0, 'ax.spines.left.visible': True, 'ax.spines.right.visible': False, 'ax.spines.bottom.visible': True, 'ax.spines.top.visible': False, 'ax.grid': False, 'ax.line0.color': '#2C3E50', 'ax.line0.linewidth': 0.8, 'ax.line0.linestyle': 'None', 'ax.line0.alpha': 0.6, 'ax.line0.marker': '_', 'ax.line1.color': '#2C3E50', 'ax.line1.linewidth': 0.8, 'ax.line1.linestyle': 'None', 'ax.line1.alpha': 0.6, 'ax.line1.marker': '_', 'ax.line2.color': '#2C3E50', 'ax.line2.linewidth': 1.5, 'ax.line2.linestyle': '-', 'ax.line2.alpha': 0.8, 'ax.line2.marker': 'None', 'ax.line3.color': '#E74C3C', 'ax.line3.linewidth': 0.8, 'ax.line3.linestyle': 'None', 'ax.line3.alpha': 0.6, 'ax.line3.marker': '_', 'ax.line4.color': '#E74C3C', 'ax.line4.linewidth': 0.8, 'ax.line4.linestyle': 'None', 'ax.line4.alpha': 0.6, 'ax.line4.marker': '_', 'ax.line5.color': '#E74C3C', 'ax.line5.linewidth': 1.5, 'ax.line5.linestyle': '-', 'ax.line5.alpha': 0.8, 'ax.line5.marker': 'None', 'ax.coll0.alpha': 0.85, 'ax.coll0.facecolors': array([[0.17254902, 0.24313725, 0.31372549, 0.85      ]]), 'ax.coll1.alpha': 0.6, 'ax.coll1.facecolors': array([], shape=(0, 4), dtype=float64), 'ax.coll2.alpha': 0.85, 'ax.coll2.facecolors': array([[0.90588235, 0.29803922, 0.23529412, 0.85      ]]), 'ax.coll3.alpha': 0.6, 'ax.coll3.facecolors': array([], shape=(0, 4), dtype=float64), 'ax.n_texts': 0, 'fig.figsize': (np.float64(9.0), np.float64(6.0)), 'fig.dpi': 150.0, 'fig.facecolor': (1.0, 1.0, 1.0, 1.0)}, _on_refresh_callbacks=[<function create_jupyter_panel.<locals>._live_refresh at 0x000001F09D23BB00>, <function create_jupyter_panel.<locals>._live_history_update at 0x000001F09D5D5800>, <function create_jupyter_panel.<locals>._live_code_update at 0x000001F09D5D6700>], _redo_stack=[])

---
## 8. 多面板对比图

将多种因果推断方法整合到单张图中，适用于学术发表。

In [33]:
# 多面板图：4 种因果推断方法并排展示
fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# 面板 A：DID 平行趋势
sp.did_plot(
    df_did, y='outcome', time='time', treat='treated',
    treat_time=6, ax=axes[0, 0],
    title='(A) 双重差分：平行趋势',
)

# 面板 B：断点回归设计
sp.rdplot(
    df_rd, y='gpa', x='test_score', c=60,
    nbins=30, ax=axes[0, 1],
    title='(B) 断点回归：奖学金 → GPA',
)

# 面板 C：合成控制轨迹
sp.synthplot(sc_result, type='trajectory',
             ax=axes[1, 0],
             title='(C) 合成控制：处理组 vs 合成组')

# 面板 D：工资与教育年限的分箱散点图
sp.binscatter(
    df_iv, y='wage', x='education',
    n_bins=20, ci=True, fit='linear',
    ax=axes[1, 1],
)
axes[1, 1].set_title('(D) 分箱散点图：工资与教育年限', fontsize=11)

fig.suptitle('StatsPAI：多方法因果推断', fontsize=15, fontweight='bold', y=1.01)
fig.tight_layout()
sp.interactive(fig)

HBox(children=(VBox(children=(Image(value=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x05j\x00\x00\x03\xf5\x…

FigureEditor(fig=<Figure size 2100x1500 with 4 Axes>, protect_data=True, edits=[], artist_roles={2132943426320: <ArtistRole.LABEL: 5>, 2132943436832: <ArtistRole.LABEL: 5>, 2132943743856: <ArtistRole.LABEL: 5>, 2132943748176: <ArtistRole.SPINE: 8>, 2132943732864: <ArtistRole.SPINE: 8>, 2132940481904: <ArtistRole.SPINE: 8>, 2132920489632: <ArtistRole.SPINE: 8>, 2132943746592: <ArtistRole.LEGEND: 7>, 2132944438000: <ArtistRole.DATA: 1>, 2132944439392: <ArtistRole.REFERENCE: 4>, 2132944441744: <ArtistRole.DATA: 1>, 2132940641376: <ArtistRole.REFERENCE: 4>, 2132933496848: <ArtistRole.ANNOTATION: 6>, 2132936987456: <ArtistRole.ANNOTATION: 6>, 2132944443760: <ArtistRole.ANNOTATION: 6>, 2132940712528: <ArtistRole.LABEL: 5>, 2132940708832: <ArtistRole.LABEL: 5>, 2132940707824: <ArtistRole.LABEL: 5>, 2132940716176: <ArtistRole.SPINE: 8>, 2132940710704: <ArtistRole.SPINE: 8>, 2132940710320: <ArtistRole.SPINE: 8>, 2132940709984: <ArtistRole.SPINE: 8>, 2132944440736: <ArtistRole.REFERENCE: 4>, 2132945147408: <ArtistRole.REFERENCE: 4>, 2132943742368: <ArtistRole.REFERENCE: 4>, 2132945056496: <ArtistRole.REFERENCE: 4>, 2132944563296: <ArtistRole.REFERENCE: 4>, 2132945151776: <ArtistRole.REFERENCE: 4>, 2132945154368: <ArtistRole.DATA: 1>, 2132945155184: <ArtistRole.DATA: 1>, 2132944439872: <ArtistRole.REFERENCE: 4>, 2132747459024: <ArtistRole.CI: 3>, 2133492107744: <ArtistRole.CI: 3>, 2132944439968: <ArtistRole.CI: 3>, 2132943744096: <ArtistRole.CI: 3>, 2132944023392: <ArtistRole.LABEL: 5>, 2132940651168: <ArtistRole.LABEL: 5>, 2132940641184: <ArtistRole.LABEL: 5>, 2132940315712: <ArtistRole.SPINE: 8>, 2132940205968: <ArtistRole.SPINE: 8>, 2132940646848: <ArtistRole.SPINE: 8>, 2132940646224: <ArtistRole.SPINE: 8>, 2132944017056: <ArtistRole.LEGEND: 7>, 2132944732384: <ArtistRole.DATA: 1>, 2132945144000: <ArtistRole.DATA: 1>, 2132944746256: <ArtistRole.REFERENCE: 4>, 2132974538048: <ArtistRole.CI: 3>, 2132944231344: <ArtistRole.LABEL: 5>, 2132944226064: <ArtistRole.LABEL: 5>, 2132944227360: <ArtistRole.LABEL: 5>, 2132944020080: <ArtistRole.SPINE: 8>, 2132944224816: <ArtistRole.SPINE: 8>, 2132944225104: <ArtistRole.SPINE: 8>, 2132944225392: <ArtistRole.SPINE: 8>, 2132974546304: <ArtistRole.REFERENCE: 4>, 2132944836736: <ArtistRole.REFERENCE: 4>, 2132974775104: <ArtistRole.DATA: 1>, 2132945148320: <ArtistRole.DATA: 1>, 2132974661424: <ArtistRole.CI: 3>, 2132944662800: <ArtistRole.LABEL: 5>}, _original_state={'ax.title.text': '(A) 双重差分：平行趋势', 'ax.title.fontsize': 13.0, 'ax.title.color': 'black', 'ax.title.fontweight': 'normal', 'ax.xlabel.text': 'Time', 'ax.xlabel.fontsize': 11.0, 'ax.xlabel.color': 'black', 'ax.ylabel.text': 'Outcome', 'ax.ylabel.fontsize': 11.0, 'ax.ylabel.color': 'black', 'ax.xlim': (np.float64(0.55), np.float64(10.45)), 'ax.ylim': (np.float64(10.157882537037665), np.float64(20.502018931687)), 'ax.facecolor': (1.0, 1.0, 1.0, 1.0), 'ax.xtick_rotation': 0.0, 'ax.ytick_rotation': 0.0, 'ax.spines.left.visible': True, 'ax.spines.right.visible': False, 'ax.spines.bottom.visible': True, 'ax.spines.top.visible': False, 'ax.grid': False, 'ax.line0.color': '#2C3E50', 'ax.line0.linewidth': 2.0, 'ax.line0.linestyle': '-', 'ax.line0.alpha': None, 'ax.line0.marker': 's', 'ax.line1.color': '#E74C3C', 'ax.line1.linewidth': 2.0, 'ax.line1.linestyle': '-', 'ax.line1.alpha': None, 'ax.line1.marker': 'o', 'ax.line2.color': '#E74C3C', 'ax.line2.linewidth': 1.5, 'ax.line2.linestyle': '--', 'ax.line2.alpha': 0.7, 'ax.line2.marker': '', 'ax.line3.color': 'gray', 'ax.line3.linewidth': 1.0, 'ax.line3.linestyle': ':', 'ax.line3.alpha': 0.5, 'ax.line3.marker': 'None', 'ax.n_texts': 3, 'ax1.title.text': '(B) 断点回归：奖学金 → GPA', 'ax1.title.fontsize': 13.0, 'ax1.title.color': 'black', 'ax1.title.fontweight': 'normal', 'ax1.xlabel.text': 'test_score', 'ax1.xlabel.fontsize': 11.0, 'ax1.xlabel.color': 'black', 'ax1.ylabel.text': 'gpa', 'ax1.ylabel.fontsize': 11.0, 'ax1.ylabel.color': 'black', 'ax1.xlim': (np.float64(0.0798728508686235), np.float64(112.14412014740388)), 'ax1.ylim': (np.float64(1.6533789207550442), np.float64(5.508840892896492)), 'ax1.facecolor': (1.0, 1.0, 1.0, 1.0), 'ax1.xtick_rotation': 0.0, 'ax1.ytick_rotation': 0.0, 'ax1.spines.left.visible': True, 'ax1.spines.right.visible': False, 'ax1.spines.bottom.visible': True, 'ax1.spines.top.visible': False, 'ax1.grid': False, 'ax1.line0.color': '#2C3E50', 'ax1.line0.linewidth': 0.8, 'ax1.line0.linestyle': 'None', 'ax1.line0.alpha': 0.7, 'ax1.line0.marker': 'o', 'ax1.line1.color': '#2C3E50', 'ax1.line1.linewidth': 0.8, 'ax1.line1.linestyle': 'None', 'ax1.line1.alpha': 0.7, 'ax1.line1.marker': '_', 'ax1.line2.color': '#2C3E50', 'ax1.line2.linewidth': 0.8, 'ax1.line2.linestyle': 'None', 'ax1.line2.alpha': 0.7, 'ax1.line2.marker': '_', 'ax1.line3.color': '#2C3E50', 'ax1.line3.linewidth': 0.8, 'ax1.line3.linestyle': 'None', 'ax1.line3.alpha': 0.7, 'ax1.line3.marker': 'o', 'ax1.line4.color': '#2C3E50', 'ax1.line4.linewidth': 0.8, 'ax1.line4.linestyle': 'None', 'ax1.line4.alpha': 0.7, 'ax1.line4.marker': '_', 'ax1.line5.color': '#2C3E50', 'ax1.line5.linewidth': 0.8, 'ax1.line5.linestyle': 'None', 'ax1.line5.alpha': 0.7, 'ax1.line5.marker': '_', 'ax1.line6.color': '#E74C3C', 'ax1.line6.linewidth': 1.5, 'ax1.line6.linestyle': '-', 'ax1.line6.alpha': None, 'ax1.line6.marker': 'None', 'ax1.line7.color': '#3498DB', 'ax1.line7.linewidth': 1.5, 'ax1.line7.linestyle': '-', 'ax1.line7.alpha': None, 'ax1.line7.marker': 'None', 'ax1.line8.color': 'gray', 'ax1.line8.linewidth': 0.8, 'ax1.line8.linestyle': '--', 'ax1.line8.alpha': 0.7, 'ax1.line8.marker': 'None', 'ax1.coll0.alpha': 0.12, 'ax1.coll0.facecolors': array([[0.90588235, 0.29803922, 0.23529412, 0.12      ]]), 'ax1.coll1.alpha': 0.12, 'ax1.coll1.facecolors': array([[0.20392157, 0.59607843, 0.85882353, 0.12      ]]), 'ax1.coll2.alpha': 0.7, 'ax1.coll2.facecolors': array([], shape=(0, 4), dtype=float64), 'ax1.coll3.alpha': 0.7, 'ax1.coll3.facecolors': array([], shape=(0, 4), dtype=float64), 'ax1.n_texts': 0, 'ax2.title.text': '(C) 合成控制：处理组 vs 合成组', 'ax2.title.fontsize': 13.0, 'ax2.title.color': 'black', 'ax2.title.fontweight': 'normal', 'ax2.xlabel.text': 'Time', 'ax2.xlabel.fontsize': 11.0, 'ax2.xlabel.color': 'black', 'ax2.ylabel.text': 'Outcome', 'ax2.ylabel.fontsize': 11.0, 'ax2.ylabel.color': 'black', 'ax2.xlim': (np.float64(1999.05), np.float64(2019.95)), 'ax2.ylim': (np.float64(47.12487078585494), np.float64(66.01208356282729)), 'ax2.facecolor': (1.0, 1.0, 1.0, 1.0), 'ax2.xtick_rotation': 0.0, 'ax2.ytick_rotation': 0.0, 'ax2.spines.left.visible': True, 'ax2.spines.right.visible': False, 'ax2.spines.bottom.visible': True, 'ax2.spines.top.visible': False, 'ax2.grid': False, 'ax2.line0.color': '#2C3E50', 'ax2.line0.linewidth': 2.2, 'ax2.line0.linestyle': '-', 'ax2.line0.alpha': None, 'ax2.line0.marker': 'None', 'ax2.line1.color': '#E74C3C', 'ax2.line1.linewidth': 2.2, 'ax2.line1.linestyle': '--', 'ax2.line1.alpha': None, 'ax2.line1.marker': 'None', 'ax2.line2.color': '#95A5A6', 'ax2.line2.linewidth': 1.2, 'ax2.line2.linestyle': ':', 'ax2.line2.alpha': 0.8, 'ax2.line2.marker': 'None', 'ax2.coll0.alpha': 0.12, 'ax2.coll0.facecolors': array([[0.90588235, 0.29803922, 0.23529412, 0.12      ]]), 'ax2.n_texts': 0, 'ax3.title.text': '(D) 分箱散点图：工资与教育年限', 'ax3.title.fontsize': 11.0, 'ax3.title.color': 'black', 'ax3.title.fontweight': 'normal', 'ax3.xlabel.text': 'education', 'ax3.xlabel.fontsize': 11.0, 'ax3.xlabel.color': 'black', 'ax3.ylabel.text': 'wage', 'ax3.ylabel.fontsize': 11.0, 'ax3.ylabel.color': 'black', 'ax3.xlim': (np.float64(7.599019194645184), np.float64(16.437878964863526)), 'ax3.ylim': (np.float64(17.835103299753403), np.float64(26.791518328274588)), 'ax3.facecolor': (1.0, 1.0, 1.0, 1.0), 'ax3.xtick_rotation': 0.0, 'ax3.ytick_rotation': 0.0, 'ax3.spines.left.visible': True, 'ax3.spines.right.visible': False, 'ax3.spines.bottom.visible': True, 'ax3.spines.top.visible': False, 'ax3.grid': False, 'ax3.line0.color': '#2C3E50', 'ax3.line0.linewidth': 0.8, 'ax3.line0.linestyle': 'None', 'ax3.line0.alpha': 0.6, 'ax3.line0.marker': '_', 'ax3.line1.color': '#2C3E50', 'ax3.line1.linewidth': 0.8, 'ax3.line1.linestyle': 'None', 'ax3.line1.alpha': 0.6, 'ax3.line1.marker': '_', 'ax3.line2.color': '#2C3E50', 'ax3.line2.linewidth': 1.5, 'ax3.line2.linestyle': '-', 'ax3.line2.alpha': 0.8, 'ax3.line2.marker': 'None', 'ax3.coll0.alpha': 0.85, 'ax3.coll0.facecolors': array([[0.17254902, 0.24313725, 0.31372549, 0.85      ]]), 'ax3.coll1.alpha': 0.6, 'ax3.coll1.facecolors': array([], shape=(0, 4), dtype=float64), 'ax3.n_texts': 0, 'fig.figsize': (np.float64(14.0), np.float64(10.0)), 'fig.dpi': 150.0, 'fig.facecolor': (1.0, 1.0, 1.0, 1.0), 'fig.suptitle.text': 'StatsPAI：多方法因果推断', 'fig.suptitle.fontsize': 15.0}, _on_refresh_callbacks=[<function create_jupyter_panel.<locals>._live_refresh at 0x000001F09F38E700>, <function create_jupyter_panel.<locals>._live_history_update at 0x000001F09F3E7600>, <function create_jupyter_panel.<locals>._live_code_update at 0x000001F09F3E6700>], _redo_stack=[])

---
## 总结

| # | 方法 | 核心函数 | 绘图函数 | 交互式 |
|---|------|---------|---------|--------|
| 1 | **双重差分法** | `sp.did(...)` | `sp.did_plot()`, `sp.event_study_plot()` | `sp.interactive(fig)` |
| 2 | **固定效应** | `sp.panel(..., method='fe')` | `sp.coefplot()` | `sp.interactive(fig)` |
| 3 | **工具变量** | `sp.ivreg("y ~ (endog ~ inst) + exog")` | `sp.coefplot()` | `sp.interactive(fig)` |
| 4 | **匹配法** | `sp.match(...)` | `sp.balanceplot()`, `sp.psplot()` | `sp.interactive(fig)` |
| 5 | **合成控制** | `sp.synth(...)` | `sp.synthplot(..., type=)` | `sp.interactive(fig)` |
| 6 | **断点回归** | `sp.rdrobust(...)` | `sp.rdplot()`, `sp.rdplotdensity()` | `sp.interactive(fig)` |
| 7 | **分箱散点图** | `sp.binscatter(...)` | 内置 | `sp.interactive(fig)` |

### 交互式编辑提示

- **本版新增**：DPI 滑块、图形大小预设、背景颜色、刻度旋转、注释、网格样式、复制到剪贴板
- 使用 `sp.get_code(fig)` 在编辑后提取可复现代码
- 所有编辑仅影响外观 —— 统计数据被锁定保护，不会被修改